withastro/language-tools

package.json, packages/language-server/src/plugins/astro/AstroPlugin.ts, packages/ts-plugin/astro.d.ts, packages/ts-plugin/package.json, packages/ts-plugin/src/astro-snapshots.ts, packages/ts-plugin/src/astro-sys.ts, packages/ts-plugin/src/astro2tsx.ts, packages/ts-plugin/src/index.ts, packages/ts-plugin/src/language-service/completions.ts, packages/ts-plugin/src/language-service/definition.ts, packages/ts-plugin/src/language-service/diagnostics.ts, packages/ts-plugin/src/language-service/find-references.ts, packages/ts-plugin/src/language-service/implementation.ts, packages/ts-plugin/src/language-service/index.ts, packages/ts-plugin/src/language-service/rename.ts, packages/ts-plugin/src/logger.ts, packages/ts-plugin/src/module-loader.ts, packages/ts-plugin/src/source-mapper.ts, packages/ts-plugin/src/utils.ts, packages/ts-plugin/tsconfig.json, packages/vscode/package.json, yarn.lock
This adds a new package, `@astrojs/ts-plugin` which is a TypeScript plugin. It runs whenever a ts/tsx/js/jsx file is open in VSCode and provides type information for .astro files, allowing prop completion from .astro files.
Loom:
https://www.loom.com/share/68ec7de42cee4fc1b20083012a2c2c57
Closes #21
=> Add TypeScript plugin

.changeset/thirty-phones-matter.md, packages/language-server/src/index.ts, packages/language-server/src/plugins/astro/AstroPlugin.ts, packages/language-server/src/plugins/typescript/languageService.ts, packages/language-server/src/plugins/typescript/utils.ts
- TypeScript internally calls us to a "sys" module that we own to search for files. We were telling it that any non-astro file needed to have a .ts extension appended. So it would keep searching for files, appending .ts many times, until ultimately giving up, but this took 300+ms.
- This fixes it by only appending the .ts for our virtual astro ts modules.
- This brings the onCompletion time down to 1-30ms.
Closes #31 
N/A
N/A
=> Improve perf for all operations

.changeset/real-parrots-ring.md, packages/vscode/syntaxes/astro.tmLanguage.json
- Gives component names a slightly different highlighting style, mirroring what Svelte does
- Closes #4
=> Provide different highlighting for component names

packages/vscode/syntaxes/astro.tmLanguage.json
- This fixes component tag name usage when there is an end tag, so that highlighting matches the self-closing case.
=> Fix highlighting of component tag when they have an end tag

.changeset/fluffy-lamps-drum.md, packages/language-server/src/plugins/typescript/features/DiagnosticsProvider.ts
- Fixes #41 
- Using blockquote like `> quote here` within the `<Markdown>` component now ignores the TS provided error about the `>` be unrecognized.
Manually, see below screenshot:
N/A
=> Fixes case of using blockquotes within Markdown component

.changeset/pretty-paws-sip.md
npm is having issues and not showing recent version of packages. Status page shows the problem: https://status.npmjs.org/
Says its fixed for new publishing, so bumping.
=> Bump language server

.changeset/selfish-suits-brush.md, packages/language-server/src/plugins/typescript/languageService.ts
- Closes #50 
- Closes #51
- Sets some defaults that TypeScript needs to recognize .astro as modern TS/JS.
=> Set default options for TypeScript

.changeset/gorgeous-socks-greet.md, packages/language-server/src/plugins/typescript/astro2tsx.ts, packages/vscode/readme.md
- Fixes #58
- Improves the Astro -> TSX translator so that we automatically insert a semi, which is needed before JSX is understood.
=> Prevent template errors when semicolons not used

.changeset/healthy-moons-compare.md, packages/language-server/astro.d.ts
- Fixes #61 
- Makes `Astro.fetchContent('/path')` default to `any`. Previously it would default to `unknown` meaning if you tried to access any properties you'd get type errors. We want to opt-in to strong typing here, so it's only strong typed if you provide a type param.
=> Make Astro.fetchContent default to any

.changeset/silver-sheep-mix.md, packages/language-server/src/plugins/typescript/astro2tsx.ts
- Makes it so that if you don't provide a Props interface export, it defaults to `any` on the usage side.
=> Default to allowing any key on component props

.changeset/heavy-rockets-remember.md, packages/language-server/src/plugins/typescript/astro2tsx.ts
- When translating to tsx and converting comments, a regex was greedy causing it to capture multiple comments rather than just the one. This fixes that.
=> Prevent greedy comment translation

.changeset/slow-dodos-flow.md, packages/language-server/src/plugins/typescript/astro2tsx.ts
- Comments that surround HTML are converted by the tsx converter, preventing errors from displaying.
=> Fix comment surrounding html

.changeset/big-oranges-perform.md, packages/language-server/src/plugins/typescript/languageService.ts
- tsconfig.json's `include` is removed before the TypeScript language server is started up. This config is intended by the user to be used with `tsc`, in this case we want all `.astro` files to be treated as TypeScript.
=> Prevent tsconfig include from interfering with diagnostics

.changeset/afraid-bananas-march.md, packages/language-server/src/plugins/typescript/astro-sys.ts, packages/language-server/src/plugins/typescript/languageService.ts
- This prevents the present of `@types/react` from interfering with how diagnostics are applied to .astro files.
- This means if you have `@types/react` installed (for jsx/tsx files) it doesn't get applied to .astro diagnostics.
=> Prevent react types from altering typescript diagnostics

.changeset/unlucky-bottles-learn.md, packages/language-server/src/plugins/PluginHost.ts, packages/language-server/src/plugins/typescript/TypeScriptPlugin.ts, packages/language-server/src/server.ts
This adds the **Rename Symbol** capability to `.astro` files.
This is only tested manually.
https://code.visualstudio.com/docs/editor/refactoring#_rename-symbol 😄
=> Basic rename implementation

.changeset/chilly-oranges-return.md, packages/language-server/src/plugins/typescript/features/HoverProvider.ts
- Starting to remove all "JSX" references, this removes "JSX attribute" on hover.
No
N/A
=> Rename JSX attribute to HTML attribute on Hover

.changeset/friendly-owls-kick.md, packages/language-server/src/check.ts, packages/language-server/src/core/documents/DocumentManager.ts, packages/language-server/src/plugins/typescript/DocumentSnapshot.ts, packages/language-server/src/plugins/typescript/LanguageServiceManager.ts, packages/language-server/src/plugins/typescript/languageService.ts, packages/language-server/src/server.ts
- TypeScript has its own snapshot manager
- When it doesn't have an existing snapshot it creates a new one by using the text from the filesystem.
- If you've already edited the document before TS creates its first snapshot (for something like hover), the document will be out of sync going forward. Depending on what you edited this could cause chaos.
- This fixes it! Prefers using existing documents in this particular case.
=> Prevent TS extension from overwriting open docs

.changeset/plenty-ladybugs-fry.md, package.json, packages/language-server/package.json, yarn.lock
This PR bumps TypeScript from `4.3.1-rc` to `4.5.1-rc` in the language extension.
To ensure a consistent developer experience, it bumps the project root to match the language extension.
bump only
bump only
=> Bump TypeScript

packages/vscode/syntaxes/astro.inject-to-markdown.tmLanguage.json
- Supports nested Astro code blocks
`````markdown
An Astro code block.
```astro
---
import Whatever from './whatever.astro'
---
<Whatever joy="lol">
<div></div>
</Whatever>
```
- A nested Astro code block.
```astro
---
import Whatever from './whatever.astro'
---
<Whatever joy="lol">
<div></div>
</Whatever>
```
- A deeply nested Astro code block.
```astro
---
import Whatever from './whatever.astro'
---
<Whatever joy="lol">
<div></div>
</Whatever>
```
An indented Astro code block.
```astro
---
import Whatever from './whatever.astro'
---
<Whatever joy="lol">
<div></div>
</Whatever>
```
`````
The above markdown in its own file.
bug fix only
=> Support nested Astro code blocks in Markdown

packages/vscode/syntaxes/astro.tmLanguage.json
- Adds support for template literal attribute values (only for syntax highlighting).
```astro
---
import Whatever from './whatever.astro'
const lol = 'awesome'
---
<Whatever one={`lol${lol}`} two=`lol${lol}`>
<div></div>
</Whatever>
```
The above astro in its own file.
bug fix only
=> Support template literal attribute values (for syntax highlighting)

.changeset/long-rice-cross.md, packages/vscode/syntaxes/astro.tmLanguage.json
- Several fixes for the syntax highlighter.
- Support for `lang="less"`, `lang="styl"`, `lang="stylus"`.
- Resolves https://github.com/withastro/astro-language-tools/issues/117
- Support for the `<>` shorthand fragment.
- Resolves https://github.com/withastro/astro-language-tools/issues/118
- Support for component names like `<Input>`, `<A.Input>`, etc.
- Improved support for attributes.
- Resolves https://github.com/withastro/astro-language-tools/issues/20
- Resolves https://github.com/withastro/astro-language-tools/issues/88
- Improved support for expression attribute values like `id=``#foo${bar}`` ` (_note: imagine single ticks_).
- Improved support for bogus HTML comments like `<?php awesome ?>`, `<?xml version="1.0" encoding="utf-8"?>`.
- Improved support for character references …
=> Several Syntax Fixes

.changeset/fast-socks-smoke.md, package.json, packages/language-server/package.json, yarn.lock
- Updates `typescript` from 4.5.1-rc to 4.5.2 (stable)
dependency update only
dependency update only
=> Upgrade TypeScript from 4.5.1-rc to 4.5.2 (stable)

.changeset/nervous-beds-mate.md, packages/language-server/astro.d.ts, packages/ts-plugin/astro.d.ts, packages/vscode/syntaxes/astro.tmLanguage.json
- This adds support for elements with namespaces.
- This adds TS support for `Fragment`.
- This adds a changeset for [support for comments](https://github.com/withastro/astro-language-tools/pull/137).
bug fix only
bug fix only
=> Various fixes

.changeset/breezy-stingrays-sing.md, packages/language-server/astro.d.ts
- Removes declarations overriding `import.meta.hot` and `import.meta.env` because these declarations are already provided by Vite.
- This removes errors that you see in the Astro repo.
Not testable.
N/A
=> Remove import.meta declarations from our d.ts

.changeset/grumpy-experts-rest.md, packages/language-server/src/plugins/typescript/languageService.ts, yarn.lock
Astro should not be reading the tsconf settings file.  This causes issues  such as `strict: true` causing ts errors like:
`JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.`
RE: https://discord.com/channels/830184174198718474/845451724738265138/895704312544653353
Closes #91.
Personal References:
- Link #T-366
- Closes #T-366
=> fix: ignore tsconfig setting files

.github/CODEOWNERS, .github/workflows/release.yml, package.json, packages/vscode/package.json
- Updates any relevant assets to point to https://github.com/withastro/language-tools
- Conforms `language-tools` with `compiler` (previously `astro-compiler`).
name update only
name update only
=> Update project from astro-language-tools to language-tools

packages/language-server/src/plugins/typescript/languageService.ts
This adds `types: ['vite/client']` to the default TypeScript config the extension uses for .astro files. What this provide us with is nice typing for `import.meta.env` without the user needing to do anything on their end
Additionally, the user can provide their own typing through [the method Vite recommend](https://vitejs.dev/guide/env-and-mode.html#intellisense-for-typescript), it work just fine (as far as I tested), as demonstrated by the screenshot below
This only add the typing for `.astro` files, the user still need to provide a `tsconfig.json` with `types: ['vite/client']` for support in other file formats (notably in our case, that includes .ts, .vue, .svelte etc files). As far as I know, they do not need to add `vite` as a dependency of their project, just the types in their …
=> Add `types: ['vite/client']` to the default tsconfig used for .astro files

package.json, packages/language-server/package.json, yarn.lock
- Updates `typescript` from `4.5.2` to `4.5.2`
- [Improvements in TypeScript 4.5.3](https://github.com/microsoft/TypeScript/issues?q=milestone%3A%22TypeScript+4.5.3%22+)
- [Improvements in TypeScript 4.5.3](https://github.com/microsoft/TypeScript/issues?q=milestone%3A%22TypeScript+4.5.4%22+)
dependency update only
dependency update only
=> Upgrade TypeScript from 4.5.2 to 4.5.4 (stable)

.changeset/witty-feet-change.md, packages/language-server/src/plugins/typescript/languageService.ts
This bring back the feature of loading the user `js/tsconfig.json` that was removed in https://github.com/withastro/language-tools/pull/144
It was removed because users with `strict: true` or `alwaysStrict: true` in their config experienced unrelated errors in .astro files (see https://github.com/withastro/language-tools/issues/91). However removing it causes other issues, most importantly, aliases don't work anymore (https://github.com/withastro/language-tools/issues/156)
This PR fix this by bringing back loading the user config but forcing `strict: false` for .astro files. Additionally, unlike the previous solution, we gently add some of our default settings through merging with the user config (so they're overwrittable if needed), for instance `type: ["vite/client"]` that was added in …
=> Bring back loading the user js/tsconfig.json

.editorconfig, .eslintignore, .eslintrc.cjs, .prettierignore, .prettierrc.json
This adds the config files used by ESLint, Prettier, EditorConfig from the main repo to this repo as well, in order to promote consistent formatting and linting across Astro project
I removed a few things from the ignores files that were applicable only to the main repo. Additionally, despite the plugins used for Prettier and ESLint, I don't think any new dependencies are needed as I think they were already installed
No tests needed
No docs needed
=> Add EditorConfig, ESLint and Prettier config files from main repo

.gitignore, CONTRIBUTING.md, README.md, lerna.json, package.json, packages/vscode/package.json, yarn.lock
This migrate the repo from Lerna to Turbo, similarly to how it was done in the main repo. Since they work similarly and all of the scripts are wrapper over it, we don't need any updates to the CI scripts (if everything goes well, computers are complicated)
Additionally, I cleaned up the dependencies, removing those that are unused. I realize that in the future, some of those might get brought back (for tests or other reasons) but I figured that for now, it was just confusing having them there and made the installation longer than it should (this change was motivated by me making this PR on coffee shop wifi)
Tests still pass (as few as they are), additionally I tested manually by running the different scripts and everything worked
Just replaced mention of Lerna with Turbo in the different …
=> Migrate to Turbo and cleanup dependencies

.changeset/famous-apes-vanish.md, packages/language-server/src/plugins/typescript/astro2tsx.ts
Before, transformations (also knowns as, `.replace`s) used when generating TSX from `.astro` files were applied to the entire file, which meant that sometimes, we'd get false positive where the regexes thinks they're transforming HTML but really they were operating on the frontmatter content. I think that in the past, this might have been allowable because we could have JSX in the frontmatter, but this isn't the case anymore 
This fixes https://github.com/withastro/language-tools/issues/155 though I reckon that this probably caused other undocumented issues for other people in the past
I realize that this is a bit of a crude fix, but then again, the original code is already a bit brittle (not that there's necessarily another way to do it without making a whole thing). In the future, I'd …
=> Apply relevant content transformations for TSX generation only in relevant parts

.changeset/heavy-dodos-brake.md, packages/language-server/src/plugins/typescript/astro2tsx.ts
Previously we were making up our TSX's template content from where the template part started in the .astro files, however what this meant is that we were missing crucial whitespace between the frontmatter and the template part. So now, we start our HTML from where the frontmatter end and not where the content starts
This fixes https://github.com/withastro/language-tools/issues/173
Tested manually and ran tests locally
(Error now appears on the right line no matter the amount of white lines before)
Bug fix only
=> Fix missing whitespace in generated TSX

.changeset/sharp-onions-tell.md, .eslintrc.cjs, packages/vscode/package.json, packages/vscode/src/index.ts
This add support for reloading the language server whenever `tsconfig.json` (and other similar files) is modified. I also added a command to manually reload the language server. This is helpful for whenever users encounter an issue where just reloading fix it (this help avoid needing to reload the entire VS Code window, which is not always pleasant to do)
The commit is a bit bigger than it should be because of formatting changes and also a small refactor removing unnecessary wrappers and abstractions. See GitHub comments on code for more info on why some changes were made
This fixes https://github.com/withastro/language-tools/issues/171
Tested manually as our tests don't cover this (not sure if it's even possible to test a VS Code extension)
No docs needed, the added command is self …
=> Add support for reloading the language server on Astro / TS config changes

.github/workflows/release.yml
- fix #16: add step to publish to OpenVSX
Someone has to configure OVSX_TOKEN secret in this repo before running the job. See https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
=> add publishing to OpenVSX

packages/vscode/src/index.ts
Previously, we splitted the path to a potential ts/jsconfig using a forward slash, I thought that was fine because I thought that VS Code normalized paths but it turns out, that: it doesn't. So we need to also split on backslashes for Windows 
Tested manually on both Windows and Linux
No docs needed
=> Fix language server reload on config changes not working on Windows

.github/workflows/release.yml
- Disables open-vsx publishing for now, as we do not have the `astro-build` publisher, that we need.
N/A
N/A
=> Disable publishing to open-vsx

.changeset/smooth-candles-rhyme.md, packages/language-server/package.json, packages/language-server/src/plugins/typescript/DocumentSnapshot.ts, packages/language-server/src/plugins/typescript/SnapshotManager.ts, packages/language-server/src/plugins/typescript/TypeScriptPlugin.ts, packages/language-server/src/plugins/typescript/utils.ts, packages/svelte-language-integration/package.json, packages/svelte-language-integration/src/index.ts, packages/svelte-language-integration/tsconfig.json, pnpm-lock.yaml
I first want to start this by giving huge thanks to @matthewp for helping me out with this because between the Document, DocumentSnapshot, DocumentFragmentSnapshot and other Java-like classes I was (and still fairly is) lost most of the time, he really helped me out figure out how to do this!
This PR adds support for importing Svelte and Vue files and for Svelte files especially, converting them to TSX and getting proper props information, like we do for Astro files. 
This setup a bigger plan to eventually allow users to add support for any kind of framework that doesn't use JSX/TSX files without needing to make changes to the language-server itself. We're not there just yet (and we probably want to make things a lot cleaner before we do that) but, this is a first step
Additionally, this …
=> Add support for importing and parsing files from frameworks

.changeset/dirty-eggs-tell.md, packages/language-server/src/plugins/PluginHost.ts, packages/language-server/src/plugins/css/CSSPlugin.ts, packages/language-server/src/server.ts, packages/language-server/test/plugins/css/CSSPlugin.test.ts
This add support for getting document colors and adding color presentations in style tags
Thanks to updating to the latest version of the CSS language service in the refactor, we benefits from hwb support, which is nice and very modern!
Tests were added for this feature in normal CSS
The values expected in the test might look weird but they're the right ones :woman_shrugging: 
No docs needed
=> Add support for document color

packages/language-server/src/plugins/typescript/language-service.ts, packages/svelte-language-integration/src/index.ts
Wrap the call to `svelte2tsx` in a try block in order to avoid the extension crashing because of a malformed Svelte component. Instead, when it doesn't work it just returns a default empty function like we do for Vue components. I alternatively tried to set the `emitOnTemplateError` to `true` but it didn't seems to work (and wouldn't be a really reliable solution anyway). 
In the future, a better fix would be to return the error from the Svelte compiler to users directly in the Astro file, that'd be neat
This also removes the forcing of `lib: ['ESNext'],` in the TypeScript config for Astro files as it didn't work in certain contexts, not sure why but this fixes the issue for now
Both fixes tested manually on repos where it didn't work previously
No docs needed
=> Fix errors with malformed Svelte components, fix missing libs in some context

packages/language-server/src/core/documents/AstroDocument.ts, packages/language-server/src/plugins/html/HTMLPlugin.ts, packages/language-server/src/plugins/html/features/astro-attributes.ts, packages/language-server/src/plugins/typescript/features/DiagnosticsProvider.ts, packages/language-server/src/plugins/typescript/language-service.ts, packages/language-server/src/plugins/typescript/snapshots/utils.ts, packages/language-server/src/utils.ts, packages/language-server/test/plugins/html/HTMLPlugin.test.ts, packages/language-server/types/astro-jsx.d.ts, packages/svelte-language-integration/src/index.ts
This add a `.d.ts` file describing our TSX output, since our diagnostics are based on those types, this bring a bunch of improvements, such as better support for Astro-specific attributes (client directives etc) on all kinds of components
Additionally, this PR add support for Hover to our HTML plugin, the reason it is done in the same PR is because without it you'd get TSX hover information when hovering HTML tags, which in addition of not being pretty or informative, might confuse users. The hover info provided by `vscode-html-languageservice` is actually pretty nice, I think users will like that a lot: 
This fixes https://github.com/withastro/language-tools/issues/164, fixes https://github.com/withastro/language-tools/issues/141, fixes …
=> Provide types for our TSX output

.changeset/chatty-garlics-jog.md, packages/language-server/src/plugins/css/CSSPlugin.ts, packages/language-server/src/plugins/css/features/astro-selectors.ts, packages/language-server/test/plugins/css/CSSPlugin.test.ts
This adds support for hover info in style tags and style attributes. Similarly to what was added for HTML in https://github.com/withastro/language-tools/pull/216
It looks like this:
This is done through `vscode-css-languageservice`, which ensure consistency with how it is done in normal `.html` and `.css` files in VS Code
This close https://github.com/withastro/language-tools/issues/218
Added tests for this feature in addition of manual testing. Additional minor tests for other CSS features were also added in this PR to ensure consistency in how features are tested
No docs needed
=> Add support for getting CSS hover info

.changeset/small-boats-cough.md, packages/language-server/src/plugins/PluginHost.ts, packages/language-server/src/plugins/typescript/TypeScriptPlugin.ts, packages/language-server/src/plugins/typescript/features/SemanticTokenProvider.ts, packages/language-server/src/plugins/typescript/snapshots/utils.ts, packages/language-server/src/plugins/typescript/utils.ts, packages/language-server/src/server.ts
This adds support for semantic tokens, they allow editors to provide additional coloring based on context. For instance, a mutable variable could now have a different coloring than a immutable one, or a method could have different coloring than a function
By default in VS Code it is only enabled if your theme support it (`editor.semanticHighlighting.enabled` is set to `"configuredByTheme"`), thankfully many themes now support it, including the default one. For more info on semantic highlighting, see [this page](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide)
This fixes https://github.com/withastro/language-tools/issues/15
This suffer from the following issue https://github.com/withastro/language-tools/issues/230, in the way that if something in a script tag …
=> Add support for semantic tokens

packages/language-server/src/core/documents/utils.ts, packages/language-server/src/plugins/css/CSSPlugin.ts, packages/language-server/src/plugins/css/features/astro-selectors.ts, packages/language-server/test/plugins/css/CSSPlugin.test.ts
We cannot reliably give CSS completions and hover info for unclosed style tags because if the HTML parser doesn't find an ending tag, it assume that the entire file is part of the tag (which is expected). This leads to completions and hover info providing invalid info (thinking that HTML tags are CSS stuff etc)
I'm not sure if this is really a needed fix because a fair assumption about editor tooling is that usually, if you give it wrong input, it gives you wrong output, but I figured that we had the power to avoid this here and that we might as well. Either way, you get an error from TypeScript telling you to close the tag, so :woman_shrugging: 
I do not think that it's the case because nowadays editors will autoclose tags for you but I wouldn't be surprised if …
=> Disable CSS completions and hover info in unclosed style tags

packages/language-server/src/plugins/html/features/astro-attributes.ts, packages/language-server/types/astro-jsx.d.ts
Adds support for `<style global>` to the language server.
There are currently no tests for specific tag attributes.
Documents the use of `global` in IDEs. I'd be happy for suggestions how the proposed wording might be improved.
=> Add support for global attribute in style tag to language server

.changeset/stupid-students-lay.md, packages/language-server/src/plugins/html/features/astro-attributes.ts, packages/language-server/types/astro-jsx.d.ts
This adds support for all the attributes added by Astro 0.26.0. [Documented here](https://docs.astro.build/en/migrate/#migrate-to-v026)
Here's how it looks when hovering a old attribute (hoist here)
Additionally, this PR fix the accepted types for EventHandler to include `string` like in HTML
Fix https://github.com/withastro/language-tools/issues/241
Tested manually (need to add tests eventually for attributes...)
No docs needed
=> Add support for Astro 0.26.0 attributes

.changeset/long-cougars-build.md, packages/language-server/package.json, packages/language-server/src/plugins/typescript/language-service.ts, packages/language-server/src/server.ts, packages/language-server/src/utils.ts, packages/language-server/test/plugins/typescript/features/SemanticTokensProvider.test.ts, yarn.lock
Add support for loading the JSX's definition file from the main repo. 
Since 1.0.0 (the version that adds the definition file to the main repo) is still in beta, this was done in a retro-compatible way where if we see that the user is using an older version of Astro, we fallback to using the ones provided in the language-server itself
Additionally, this add notifications for when we detect an old version of Astro that is unsupported (anything before 0.24.5) telling users to either upgrade Astro to a supported version or downgrade the extension. 
A notification was also added for when we don't detect Astro at all, which is an interesting situation right now because the extension actually still works (apart from the types from `env.d.ts`) but is not really a situation we actually support …
=> Add support for loading main repo's JSX definition file

.changeset/unlucky-llamas-promise.md, packages/language-server/src/plugins/typescript/features/DiagnosticsProvider.ts, packages/language-server/test/plugins/typescript/TypeScriptPlugin.test.ts, packages/language-server/test/plugins/typescript/features/DiagnosticsProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/diagnostics/astroJSXDefinitions.astro, packages/language-server/test/plugins/typescript/fixtures/diagnostics/astroTypes.astro, packages/language-server/test/plugins/typescript/fixtures/diagnostics/basic.astro, packages/language-server/test/plugins/typescript/fixtures/diagnostics/hints.astro, packages/language-server/test/plugins/typescript/fixtures/diagnostics/multipleComments.astro, packages/language-server/test/plugins/typescript/fixtures/diagnostics/slots.astro, packages/language-server/test/plugins/typescript/fixtures/diagnostics/ssrReturn.astro, packages/language-server/test/utils.ts
Ignore the "Can't return outside of a function body" diagnostic. While it is technically a valid diagnostic, unfortunately due to how our TSX is formed, the frontmatter is at the top level and thus any return there will create this issue
This wasn't a problem before as we never returned from the frontmatter but now with the addition of SSR, this is something that users might do
There's still an issue where unconditional returns will result in TypeScript telling us the entire template is unreachable code, which is currently right, as returning a Response does not return the template. However in the future this will change if we were to support returning in the frontmatter while still using the template
Hopefully by then, we'll have a different TSX output :sweat_smile:
No …
=> Ignore "Can't return outside of a function body" diagnostic

.changeset/lucky-pans-stare.md, packages/language-server/src/plugins/typescript/astro2tsx.ts, packages/language-server/src/plugins/typescript/features/DiagnosticsProvider.ts, packages/language-server/test/plugins/typescript/features/DiagnosticsProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/diagnostics/noMarkdown.astro
Makes it so our TSX transformer transform Markdown tags into template literal, like it does for style tags
This is necessary because otherwise, TypeScript interpret the content of Markdown as JSX and print some errors, try to provide hover info etc. This is not a perfect solution as some users might actually want JSX in their Markdown but it's hard for TypeScript to understand what is wanted JSX and what is not so I think this is for the best 
I alternatively tried to just ignore diagnostics in Markdown tags but I felt like having to add a "isNotInMarkdown" condition to every single TypeScript feature would get annoying and redundant when we could do this
This PR includes a slight refactor to our diagnostic provider in the typescript plugin, removing a few svelte-ism and adding comments …
=> Transform Markdown tags to template literal

.changeset/chatty-kiwis-applaud.md, packages/language-server/src/plugins/interfaces.ts, packages/language-server/src/plugins/typescript/TypeScriptPlugin.ts, packages/language-server/src/plugins/typescript/features/FoldingRangesProvider.ts, packages/language-server/test/plugins/typescript/TypeScriptPlugin.test.ts, packages/language-server/test/plugins/typescript/features/FoldingRangesProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/foldingRanges/excludedtags.astro, packages/language-server/test/plugins/typescript/fixtures/foldingRanges/frontmatter.astro
Add support for folding JavaScript, with this everything is now fold-able (HTML, CSS, JavaScript and frontmatter)!
Support include frontmatter and expressions. Folding inside of script tags is currently not supported (require https://github.com/withastro/language-tools/issues/230)
Tests added
No docs needed (no settings needed as we don't support disabling folding ranges (there's not much point to disabling them..)
=> Add support for folding ranges for JavaScript

.changeset/grumpy-pigs-raise.md, packages/language-server/src/plugins/astro/features/CompletionsProvider.ts, packages/language-server/test/plugins/astro/features/CompletionsProvider.test.ts
Misc improvements to the completions provided by the Astro plugins to better match the TypeScript plugin after https://github.com/withastro/language-tools/pull/253
Depending on the type of the prop, we now give a different insertText. We also show the type on the right hand side of the completion, which is neat
No tests needed, we don't have dedicated tests for this but our current tests cover this
No docs needed
=> Misc improvements to Astro plugin completions

.changeset/four-laws-occur.md, packages/language-server/src/server.ts
If server settings were not provided to the Astro LS, it would crash with:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Request initialize failed with message: Cannot read properties of undefined (reading 'astro')"}}
```
This fixes this issue by adding a null check to the server settings.
(I ran into this issue with my configuration of Neovim LSP.)
Does this need tests at all?
I'm not exactly sure how to go about testing this, anyway, since `configManager` isn't even used in `LanguageServiceManager`.
It's just a bug fix, no docs necessary.
=> fix: handle the case when server settings are not provided

.changeset/lemon-kids-design.md, packages/language-server/src/plugins/html/features/astro-attributes.ts, packages/language-server/test/plugins/astro/features/CompletionsProvider.test.ts
This adds a few missing attributes in our HTML definitions, also updates the links to the new directive reference. "Astro documentation" was changed to "Astro reference" to match the changes done in https://github.com/withastro/astro/pull/3042
A PR on the JSX definition in the main repo will follow to add the types
No tests needed
No docs needed
=> Update HTML attributes definitions

packages/language-server/src/plugins/css/CSSPlugin.ts, packages/language-server/test/plugins/css/CSSPlugin.test.ts, packages/vscode/src/index.ts
We never told VS Code that we want the Emmet config which meant that we never got VS Code's default settings which allows for extended completions (things like `a:link` and others) :sweat: 
This PR also adds support for Emmet in CSS, giving us Emmet support everywhere now! :partying_face:
This fix https://github.com/withastro/language-tools/issues/9
The support in CSS has some minors issues due to upstream issues but since those issues seems to shows up in every single VS Code extension that depend on the official VS Code Emmet helper, I figured it was alright
The issues are fairly minor in the grand scheme of things, being things like completions showing when they shouldn't and completions with `+` not working properly (which also happens in the official Emmet extension bundled with VS …
=> Fix Emmet settings not being loaded, add Emmet support in CSS

.changeset/kind-turkeys-remain.md, packages/language-server/src/plugins/PluginHost.ts, packages/language-server/src/plugins/typescript/TypeScriptPlugin.ts, packages/language-server/src/plugins/typescript/features/CodeActionsProvider.ts, packages/language-server/src/plugins/typescript/features/CompletionsProvider.ts, packages/language-server/src/plugins/typescript/features/utils.ts, packages/language-server/src/plugins/typescript/utils.ts, packages/language-server/src/server.ts, packages/language-server/src/utils.ts, packages/language-server/test/plugins/typescript/TypeScriptPlugin.test.ts, packages/language-server/test/plugins/typescript/features/CodeActionsProvider.test.ts, packages/language-server/test/plugins/typescript/features/CompletionsProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/codeActions/basic.astro, packages/language-server/test/plugins/typescript/fixtures/codeActions/quickFixImportComponent.astro, packages/language-server/test/plugins/typescript/fixtures/codeActions/sortOrganizeImports.astro
This adds support for TypeScript code actions! Code actions are what powers features such as "Quick fixes" and "Source actions" in the editor.
This works everywhere in the file, frontmatter, jsx expressions, template etc. It also support the Organize Imports and Sort Imports actions
This PR also fix an issue where the first completion that add an import would mistakenly add it on the wrong line (due to the shape of our TSX output)
This fix https://github.com/withastro/language-tools/issues/143
I decided against implementing some code actions that are available in TypeScript, at least for this first implementation. Notably, I did not implement refactors and the fix all code action. 
- Refactors in TypeScript are not too good, even in `ts` files some patterns will break them. Other …
=> Implement TypeScript code actions

package.json, packages/language-server/src/core/config/ConfigManager.ts, packages/language-server/src/core/config/interfaces.ts, packages/language-server/src/plugins/css/CSSPlugin.ts, packages/language-server/src/plugins/html/HTMLPlugin.ts, packages/language-server/src/plugins/html/features/astro-attributes.ts, packages/language-server/src/plugins/typescript/TypeScriptPlugin.ts, packages/language-server/src/plugins/typescript/features/CodeActionsProvider.ts, packages/language-server/src/plugins/typescript/features/CompletionsProvider.ts, packages/language-server/src/server.ts, packages/language-server/test/plugins/css/CSSPlugin.test.ts, packages/language-server/test/plugins/html/HTMLPlugin.test.ts, packages/language-server/test/plugins/typescript/TypeScriptPlugin.test.ts, packages/language-server/test/plugins/typescript/features/CodeActionsProvider.test.ts, packages/language-server/test/plugins/typescript/features/CompletionsProvider.test.ts, packages/vscode/package.json, packages/vscode/src/index.ts, yarn.lock
Configuration in language servers can work in two modes: push and pull. The former is what we're currently doing, where the client will push settings to the server at initialization, this mode is deprecated in favor of the later, pull. 
In that mode, the server will pull configurations sections from the client, [this does not make people necessarily happy](https://github.com/microsoft/language-server-protocol/issues/972) and it is in fact, not as easy as implement and use as the previous mode but it allows for per-workspace and per-document settings, which is nice
So this PR migrates to pull mode, additionally this PR includes a refactor to our settings definitions inside the VS Code's extension `package.json` to make sure every settings is there with the proper names. Some settings were …
=> Overhaul Config Management

.changeset/itchy-eyes-hear.md, packages/language-server/src/plugins/astro/AstroPlugin.ts, packages/language-server/src/plugins/astro/features/CompletionsProvider.ts, packages/language-server/test/plugins/astro/features/CompletionsProvider.test.ts, packages/language-server/test/plugins/astro/fixtures/completions/JSXComponentDTS.d.ts, packages/language-server/test/plugins/astro/fixtures/completions/JSXComponentDTS.jsx, packages/language-server/test/plugins/astro/fixtures/completions/component.astro, packages/language-server/test/plugins/astro/fixtures/tsconfig.json
This PR does a few things to the Astro plugin's completions :sweat_smile:
- Add support for getting props from `.d.ts` files, for transpiled `jsx` components (this was discovered through Ben's stream on FrontendHorse where Prismic didn't get completions)
- Improve performance for getting props completions, I added a cache (like the TS's completions) and additionally removed additional unnecessary TS calls as they're super expensive. In local, this made the completion about 150-200ms(!) faster
- Removed `-` as a commit character for the frontend completions. It's not possible for a commit character to not be included in the completion, which meant that users would end up with one too many dash after using the frontmatter completion
- Misc refactors
**Note:**
Getting types from complex …
=> Add support for props completions from `.d.ts` files, improve performance

.changeset/quiet-olives-appear.md, packages/language-server/package.json, packages/language-server/src/core/config/ConfigManager.ts, packages/language-server/src/plugins/PluginHost.ts, packages/language-server/src/plugins/interfaces.ts, packages/language-server/src/plugins/typescript/TypeScriptPlugin.ts, packages/language-server/src/plugins/typescript/features/CompletionsProvider.ts, packages/language-server/src/plugins/typescript/features/InlayHintsProvider.ts, packages/language-server/src/server.ts, packages/language-server/test/plugins/typescript/TypeScriptPlugin.test.ts, packages/language-server/test/plugins/typescript/features/InlayHintsProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/inlayHints/basic.astro, packages/language-server/test/plugins/typescript/fixtures/inlayHints/scriptTag.astro, packages/vscode/package.json, packages/vscode/src/index.ts, yarn.lock
This adds support for [inlay hints](https://code.visualstudio.com/docs/languages/typescript#_inlay-hints)! This requires upgrading the versions of a few things as inlay hints support was only added in the latest version of the LSP. Those versions are stable, as they've been through a lot of testing (and are already in use by other extensions)
Tests added
No docs needed, inlayHints are enabled using the same configuration they're enabled with in TypeScript files
=> Add support for inlay hints

.changeset/witty-melons-count.md, packages/language-server/src/plugins/astro/features/CompletionsProvider.ts, packages/language-server/src/plugins/typescript/features/CompletionsProvider.ts, packages/language-server/test/plugins/astro/features/CompletionsProvider.test.ts, packages/language-server/test/plugins/astro/fixtures/completions/optional.astro, packages/language-server/test/plugins/astro/fixtures/completions/optionalProps.astro
This makes it so a `?` is added to optional parameters inside completions, like it does inside `.ts` files. Also added this for props, like in JSX files. Optional props are now sorted below required ones
This makes a really nice result for components with many props, such as `astro-eleventy-img`'s `<Image>`
Updated tests with new sorting text, added new test for components
No docs needed
=> Properly mark optional parameters with a `?`

.changeset/rare-cameras-wash.md, packages/language-server/package.json, packages/language-server/src/plugins/typescript/snapshots/utils.ts, packages/language-server/test/plugins/astro/features/CompletionsProvider.test.ts, packages/language-server/test/plugins/astro/fixtures/completions/VueComponent.vue, packages/language-server/test/plugins/astro/fixtures/completions/VueComponentTS.vue, packages/language-server/test/plugins/astro/fixtures/completions/component.astro, packages/vue-language-integration/package.json, packages/vue-language-integration/src/index.ts, packages/vue-language-integration/tsconfig.json, yarn.lock
This adds support for getting props from Vue files, similar to what we do for Svelte. Unfortunately, there's about 6 ways you can define props inside a Vue 3 component and it's not very possible for us to support all them. So I decided to focus on supporting the ones that are the most used. 
As such, we only support the following inside `script setup` (so Composition API):
Non-TS way:
```vue
<script setup>
defineProps({
name: { type: String, required: true },
})
</script>
```
TS-way:
```vue
<script setup lang="ts">
defineProps<{name: string}>()
</script>
```
&
```vue
<script setup lang="ts">
interface Props {
name: string
}
defineProps<Props>()
</script>
```
This fixes https://github.com/withastro/language-tools/issues/169
(JSX props errors are already insanely verbose and for Vue …
=> Add support for props completions and type checking for Vue components

.changeset/orange-chicken-march.md, packages/language-server/package.json, packages/language-server/src/core/config/ConfigManager.ts, packages/language-server/src/core/config/interfaces.ts, packages/language-server/src/plugins/PluginHost.ts, packages/language-server/src/plugins/html/HTMLPlugin.ts, packages/language-server/src/plugins/typescript/TypeScriptPlugin.ts, packages/language-server/src/plugins/typescript/features/FormattingProvider.ts, packages/language-server/src/server.ts, packages/language-server/test/plugins/html/HTMLPlugin.test.ts, packages/language-server/test/plugins/typescript/TypeScriptPlugin.test.ts, packages/language-server/test/plugins/typescript/features/FormattingProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/formatting/basic.astro, packages/language-server/test/plugins/typescript/fixtures/formatting/scriptTag.astro, packages/language-server/test/utils.ts, packages/vscode/package.json, yarn.lock
This adds formatting support to the language server. Powered by vscode-html-languageservice and TypeScript. It's pretty 1:1 with the formatting VS Code provide by default inside HTML and JavaScript files, so users used to that will feel right at home, especially since it respect the user's settings for that
The formatting provided is clearly not perfect, as it's mostly intended for HTML and not for JSX (even less so Astro's kind of JSX), however I found the results to be frankly pretty good in most cases (tested using various files for the docs and other examples)
Since it uses Microsoft's API for formatting, it's fairly maintenance-less and it wasn't necessarily hard to implement either
I tested as many pages from real-world usage as I could (our docs, my website etc) and found no case …
=> Add support for formatting

.changeset/tiny-radios-train.md, packages/language-server/src/plugins/PluginHost.ts, packages/language-server/src/plugins/html/HTMLPlugin.ts, packages/language-server/src/server.ts, packages/language-server/test/plugins/html/HTMLPlugin.test.ts
Simple PR adding support for linked editing inside HTML, it's powered by our usual HTML service and as such, matches VS Code's behavior inside HTML files, down to its downfalls (ex: if you type too fast before the linked range appear, it doesn't work)
This feature is unfortunately disabled by default inside VS Code, not sure why. It's also not very pretty, but it's really useful when you have it enabled!
Added a test
No docs needed
=> Add support for Linked Editing

.changeset/wet-lizards-knock.md, packages/language-server/test/plugins/typescript/features/HoverProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/hoverInfo/svelteComment.astro, packages/language-server/test/plugins/typescript/fixtures/hoverInfo/svelteComment.svelte, packages/svelte-language-integration/src/index.ts
Svelte components can be documented using an HTML comment inside the template with a `@component` directive. However, due to how we form our TSX output, the resulting JSDoc comment from svelte2tsx would end up in the wrong place and it wouldn't show when users hovered Svelte components. This PR fix this
Added a test
No docs needed
=> Add support for Svelte components documentation

.changeset/beige-glasses-complain.md, packages/language-server/src/plugins/typescript/features/DiagnosticsProvider.ts, packages/language-server/src/plugins/typescript/language-service.ts, packages/language-server/src/plugins/typescript/utils.ts, packages/language-server/test/plugins/typescript/features/CodeActionsProvider.test.ts, packages/language-server/test/plugins/typescript/features/DiagnosticsProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/codeActions/scriptTag.astro, packages/language-server/test/plugins/typescript/fixtures/diagnostics/scriptTagTypeScript.astro
Editor tooling part of https://github.com/withastro/astro/pull/3665. 
This was not implemented in a retro-compatible way, which mean that users using outdated Astro versions might run into false-positive where TS doesn't properly report that TS is not supported inside script tags, I think that's okay since it shouldn't happen too often (and we're <1.0 still)
Added a test for this, updated tests that needed changes
No docs needed on our side, planning PR / collab for docs update however
=> Add support for TypeScript inside hoisted script tags

.changeset/gold-rocks-hear.md, packages/language-server/src/core/config/ConfigManager.ts, packages/language-server/src/core/config/interfaces.ts, packages/language-server/src/plugins/typescript/LanguageServiceManager.ts, packages/language-server/src/plugins/typescript/language-service.ts, packages/language-server/src/server.ts, packages/language-server/test/plugins/typescript/features/DiagnosticsProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/diagnostics/arbitraryAttrs.astro, packages/language-server/types/arbitrary-attrs.d.ts, packages/vscode/package.json
This adds a setting `astro.typescript.allowArbitraryAttributes` to enable support for non-standard attributes. This is part of the puzzle to support frameworks that want users to add attributes to HTML elements such as Alpine and petite-vue
Additionally, while testing this I realized that there was an issue where for clients that don't support `workspace/configuration`, every single `getConfig` call that used a path instead of a simple string (ex: `astro.format` instead of `astro`) would return `undefined` so I fixed that
Added a test
The added setting has a description and a title to indicate what it does and when it can be useful
=> Add config setting to support arbitrary attributes

.changeset/twelve-roses-hammer.md, packages/language-server/package.json, packages/language-server/src/core/config/ConfigManager.ts, packages/language-server/src/plugins/PluginHost.ts, packages/language-server/src/plugins/css/CSSPlugin.ts, packages/language-server/src/plugins/typescript/features/CodeActionsProvider.ts, packages/language-server/src/plugins/typescript/features/CompletionsProvider.ts, packages/language-server/src/utils.ts, packages/language-server/test/plugins/PluginHost.test.ts, yarn.lock
This completely removes Lodash from the language-server codebase, lighten up the files count significantly (Lodash is 1000+ files)
Tests still pass, added a test suite for the entire PluginHost
No docs needed
=> Remove Lodash from codebase

.changeset/violet-deers-warn.md, packages/language-server/src/core/documents/utils.ts, packages/language-server/src/plugins/PluginHost.ts, packages/language-server/src/plugins/astro/features/CompletionsProvider.ts, packages/language-server/src/plugins/html/HTMLPlugin.ts, packages/language-server/src/plugins/typescript/features/CompletionsProvider.ts, packages/language-server/src/utils.ts, packages/language-server/test/plugins/typescript/features/CompletionsProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/completions/importNamespacedComponents.astro, packages/language-server/test/plugins/typescript/fixtures/completions/imports/MultipleComponent.jsx
Updated component check so we can get completions after the dot in `<thing.>`. This allows notably to get completion for components under a namespace and also for the `Content` component when importing Markdown (either through a dynamic imports or through `Astro.glob`)
Additionally, this made it so I could remove some unused helper functions, codebase is now smaller!
Added a test
No docs needed
=> Update component check so completions work inside namespaced components

.changeset/little-chefs-enjoy.md, packages/language-server/src/core/config/ConfigManager.ts, packages/language-server/src/core/config/interfaces.ts, packages/language-server/src/plugins/css/CSSPlugin.ts, packages/language-server/src/plugins/html/HTMLPlugin.ts
Settings now work on an "opt-out" basis, where if a specific settings isn't provided, it'll fallback to its default value (which for features, means enabled)
The reason for this change is that in clients where you use the language server directly, for instance Neovim, the language server will in most cases be started with no settings at all and it's annoying for users to need to enable features all explicitly. For VS Code, this does not change anything because it always ship with all the settings at their default values
This is covered already by our tests (if this broke feature checks, pretty much every test would fail). Additionally, we already have tests that test when features are disabled
No docs needed. I'll inform people in Discord about the change for those who asked about it
=> Update default settings behaviour when no settings are provided

CONTRIBUTING.md, README.md, package.json, yarn.lock
While working on https://github.com/withastro/language-tools/pull/332, I noticed our Prettier version was so outdated, it couldn't parse the `importPackage.ts` file because of the `import type * from x` line 😐 
This PR updates both Prettier and ESLint (and the plugins we use for both) to their latest versions. Running Prettier showed no changes apart from misc Markdown files
N/A. Running ESLint and Prettier showed no major changes
N/A
=> chore: Update Prettier and ESLint

.changeset/nasty-ants-search.md, packages/language-server/src/check.ts, packages/language-server/src/index.ts
Some new exports are necessary from the language server for https://github.com/withastro/astro/pull/3906
Additionally, this add the ability to pass a config when initializing the AstroCheck, this will be useful to support config parameters that changes diagnostics (ex: `astro.typescript.allowArbitraryAttributes`)
N/A
N/A
=> Update exports for astro check

.changeset/tough-poets-compare.md, packages/language-server/package.json, packages/language-server/src/plugins/typescript/features/DiagnosticsProvider.ts, packages/language-server/src/plugins/typescript/language-service.ts, packages/language-server/test/plugins/typescript/features/DiagnosticsProvider.test.ts, yarn.lock
This PR does two things:
- Updated the default configuration we force in `.astro` files so we properly include all the needed files from `node_modules`
- Updated ignored codes so we don't mistakenly ignore TypeScript's hint about a module being implicitly any because it has no types
Together, this should lead to a more accurate and closer to `.ts` files experience
Tests already cover this, https://github.com/withastro/astro/pull/3927 is required before the current tests pass however
N/A
=> Update default settings to make sure we properly include needed files

.changeset/friendly-ducks-joke.md, packages/language-server/src/plugins/typescript/language-service.ts, packages/language-server/src/server.ts, packages/language-server/src/utils.ts, packages/language-server/test/fixtures/astro-workspace/package.json, packages/language-server/test/utils.test.ts
Before checking if Astro is present in one of the opened workspaces, we now first check that it's actually an Astro workspace to see if our warning will be relevant or not
Fix https://github.com/withastro/language-tools/issues/296
Tested manually + added a test for the utility
N/A
=> Fix abusive warnings inside non-Astro workspaces

.changeset/violet-beds-begin.md, packages/vscode/src/index.ts
Fixed the server restarting while trying to send a notification about an updated Astro config. Reloading when the Astro config is changed is unnecessary in our case as we don't do any special behaviour for it (`astro-preproces` when?)
Additionally, this PR adds `json` as a file format to send notifications about, which fix cache issues with JSON modules
The client part of this notification is unfortunately currently untested, the server part is however partly tested
N/A
=> Fix notification fail when updating the Astro project's config

.changeset/brown-taxis-look.md, packages/language-server/src/core/documents/utils.ts, packages/language-server/src/plugins/PluginHost.ts, packages/language-server/src/plugins/html/HTMLPlugin.ts, packages/language-server/src/plugins/html/features/astro-attributes.ts, packages/language-server/src/plugins/typescript/features/CompletionsProvider.ts, packages/language-server/test/plugins/PluginHost.test.ts, packages/language-server/test/plugins/fixtures/pluginHostCompletions/AstroComponent.astro, packages/language-server/test/plugins/fixtures/pluginHostCompletions/VueComponent.vue, packages/language-server/test/plugins/fixtures/pluginHostCompletions/astroAndTS.astro, packages/language-server/test/plugins/fixtures/tsconfig.json, packages/language-server/test/utils.ts
This PR does two things:
- Fix the completion filtering logic so that we don't accidentally filter completions inside script tags
- Update the completion filtering logic so that some duplicated completions are now fixed and some uninteresting completions are now filtered
Additionally, this PR remove some now unnecessary logic that manually added extensions to auto imports inside script tags.
Added tests for filtering completions in the start of components
N/A
=> Fix completions not working inside script tags, fix abusive completions

packages/language-server/package.json, packages/language-server/test/plugins/typescript/features/DiagnosticsProvider.test.ts, packages/language-server/test/plugins/typescript/features/HoverProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/diagnostics/SvelteOptionalProps.svelte, packages/language-server/test/plugins/typescript/fixtures/diagnostics/svelteOptional.astro, yarn.lock
Requires https://github.com/withastro/astro/pull/3993 to be merged in and released before the tests pass
Add some tests that we properly support optional props for Svelte components
It's tests
N/A
=> Add tests for optional props on Svelte components

.changeset/hip-shirts-sneeze.md, packages/vscode/src/index.ts
The check in https://github.com/withastro/language-tools/pull/346 wasn't written properly and was never true, oops. This issue is annoying to test because it doesn't happen in dev
N/A
=> Fix extension failing to send a notification when `tsconfig.json` is updated

.changeset/twelve-timers-build.md, packages/language-server/src/plugins/typescript/language-service.ts
This makes it so we don't use `tsconfig.json`'s `types` field to add Astro's types, instead the files are added to the project directly. This makes it so `types` is no longer explicit by default even if the users has `types` unset in their config
Fix https://github.com/withastro/language-tools/issues/345
Tests still pass!
N/A
=> Don't use TypeScript's types field to add Astro types

.changeset/little-ties-matter.md, packages/language-server/src/plugins/typescript/TypeScriptPlugin.ts, packages/language-server/src/plugins/typescript/astro2tsx.ts, packages/language-server/src/plugins/typescript/snapshots/utils.ts, packages/language-server/src/server.ts, packages/vscode/package.json, packages/vscode/src/index.ts
Gone are the days of adding a `console.log` to `astro2tsx`. We now have a convenient command to show the output. Will be very convenient for helping people out
N/A, debug command
Commands are self-documented
=> Add a debug command to show the current document's TSX output

.changeset/healthy-dancers-repeat.md, packages/language-server/README.md, packages/language-server/src/importPackage.ts, packages/language-server/src/plugins/typescript/language-service.ts, packages/language-server/src/server.ts, packages/language-server/src/utils.ts, packages/language-server/types/README.md, packages/language-server/types/astro-jsx.d.ts, packages/language-server/types/env.d.ts
~~- Bring Solid as a dependency~~
- Make our error handling when not being able to load types and modules from Astro and integrations much more robust. Previously, if the `@astrojs/svelte|vue` packages were installed but were too old / somehow broken, the language server would completely freeze up, now it'll show an error and keep going with its language server life
- Improve support for monorepos, weird workspaces, our monorepo. *Everything* should work in our monorepo now
- Much better support for workspaces where Astro is not installed, now we'll gracefully fallback to internal types that are of course not as good as the ones in Astro, but serviceable when just trying out `.astro` files or showcasing on streams etc. A notification will still be shown to warn user that the experience is …
=> Solidify loading types from Astro

.changeset/ninety-rice-bow.md, packages/language-server/src/check.ts, packages/language-server/src/plugins/astro/AstroPlugin.ts, packages/language-server/src/plugins/typescript/TypeScriptPlugin.ts, packages/language-server/src/server.ts, packages/language-server/test/plugins/PluginHost.test.ts, packages/language-server/test/plugins/typescript/TypeScriptPlugin.test.ts, packages/language-server/test/plugins/typescript/features/misc/alias.test.ts, packages/language-server/test/plugins/typescript/fixtures/misc/alias.astro, packages/language-server/test/plugins/typescript/fixtures/misc/components/BehindAnAlias.astro, packages/language-server/test/plugins/typescript/fixtures/tsconfig.json
- Fix workspaces paths not being normalized, which lead to `tsconfig.json` not loading properly on Windows due to file URLs being wrong
- Small refactor to avoid making two LanguageServiceManager
Fix https://github.com/withastro/language-tools/issues/364
Added a test for aliases, updated tests for refactors
N/A
=> Fix tsconfig.json not loading properly on Windows

.changeset/healthy-parents-fly.md, .eslintrc.cjs, packages/vscode/package.json, packages/vscode/src/index.ts
closes #370 
- adds and implements `astro.langauge-server.ls-path` setting
- adds and implements `astro.language-server.runtime` setting
Ran locally with the instructions from `./CONTRIBUTING.md` inside a project with PnP enabled
No docs were updated, doesn't look like the settings are necessary documented anywhere inside the codebase
=> [feature] yarn berry support (#370)

.changeset/seven-cows-sit.md, packages/language-server/src/server.ts
Due to a missing `?`, the language server failed to open whenever no init params were passed at all. This fix this
Fix https://github.com/withastro/language-tools/issues/369
N/A. Plan to write docs about init options in the future
=> Fix language server when not init options were passed

.changeset/olive-books-sing.md, packages/vscode/package.json
Due to a bug in VS Code's TextMate engine where unbalancedBracketScopes are not respected inside embedded languages and https://github.com/microsoft/vscode/pull/151705, syntax highlighting doesn't work correctly in VS Code 1.70 inside Astro files inside expressions. This workaround this issue by manually adding TypeScript's unbalancedBracketScopes to our grammar definition
This workaround was also done by the Vue and Svelte teams to their respective grammar, so it should be safe to do for us too
Tested manually as we can't test this in our suite since it happens inside an embedded language
N/A
=> Fix highlighting regression since VS Code 1.70

.changeset/spotty-bulldogs-tell.md, packages/language-server/src/plugins/html/HTMLPlugin.ts, packages/language-server/test/plugins/html/HTMLPlugin.test.ts
Fixed completions for HTML attributes not working anymore since 0.20.3. Attributes have no description, so we were filtering them out accidentally We didn't have a test for this, so we didn't catch that regression, unfortunately.
Added a test
N/A
=> Fix regression related to completions for HTML attributes

.changeset/stale-geese-jam.md, packages/language-server/src/plugins/typescript/astro2tsx.ts, packages/language-server/test/plugins/typescript/features/DiagnosticsProvider.test.ts, packages/language-server/test/plugins/typescript/features/SemanticTokensProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/diagnostics/propsTypes.astro, packages/language-server/test/plugins/typescript/fixtures/semanticTokens/frontmatter.astro
When a `Props` interface/type is available, we'll now type `Astro.props` on the Astro global with it automatically. The type is not strict, it's `Record<string, any> & Props`. We could make it strict, but it would require to copy the JSDoc definition of `Astro.props` in the language-server (and in the future, the compiler), which is fine but a bit annoying
Added a test
N/A
=> Automatically type `Astro.props` using the Props interface when available

.changeset/neat-turtles-sleep.md, packages/language-server/src/core/config/ConfigManager.ts, packages/language-server/src/plugins/astro/AstroPlugin.ts
When available, we'll now load settings from the Prettier VS Code extension, (ex: `prettier.semi`). Our settings cascade matches the one of the Prettier VS Code extension in that if a Prettier config file is available, we'll completely ignore everything else. This should lead to a consistent experience between all files no matter if they use the Astro extension to format or the Prettier VS Code extension
Fix https://github.com/withastro/language-tools/issues/390
Tested manually in addition to current tests
N/A
=> Load settings from the Prettier VS Code extension when it's available

.changeset/fluffy-dolls-sell.md, packages/language-server/src/core/config/ConfigManager.ts, packages/language-server/src/server.ts
We were wrongfully still using `workspace.getConfiguration` even on clients that didn't announce supporting `workspace/configuration`. This fix that
Tested manually, we don't have a test setup for this right now (and all common clients support `workspace/configuration`
N/A
=> Dont use workspace config when not supported

.changeset/gentle-spies-flash.md, packages/language-server/src/core/documents/AstroDocument.ts, packages/language-server/src/core/documents/parseHtml.ts, packages/language-server/src/core/documents/utils.ts, packages/language-server/test/plugins/html/HTMLPlugin.test.ts
Makes it so we blank <> inside the frontmatter when doing HTML parsing to avoid them messing with the HTML AST. 
Ultimately, we should probably have the compiler do the HTML parsing and AST for us to avoid those kinds of issues, as there's still remaining issues when <> are used inside the template (ex: TypeScript generics) 
Added a test
N/A
=> Fix <> inside the frontmatter messing with the HTML parsing

.changeset/pink-coats-applaud.md, .vscode/launch.json, packages/vscode/package.json, packages/vscode/src/browser.ts
Load the server web module using the `?target=web` query param to make sure it loads the proper version when distributed on the web (otherwise it loads the browser module of the node version, which is empty). In local with the web extension host the query param is just ignored, so there's no need to apply this conditionally 
Added some deprecation messages to the old formatting settings
=> Load web module from ?target=web

.changeset/twenty-bats-visit.md, packages/language-server/src/plugins/astro/features/CompletionsProvider.ts, packages/language-server/src/plugins/html/HTMLPlugin.ts, packages/language-server/src/plugins/html/features/astro-attributes.ts, packages/language-server/test/plugins/PluginHost.test.ts
Update completions on the Fragment element to not have client directives and the slot attribute. Also added the slot attributes to all components
Before:
After: 
Updated tests
N/A
=> Improve completions on the Fragment element, add completions for slot on components

.changeset/twenty-gifts-double.md, packages/vscode/syntaxes/astro.tmLanguage.json, packages/vscode/test/grammar/fixtures/script/events.astro, packages/vscode/test/grammar/fixtures/script/events.astro.snap
Add support for highlighting the inside of events handlers as JavaScript, like in HTML files
(TypeScript isn't supported inside events handlers, I was just messing around)
Added a test
N/A
=> Add support for syntax highlighting events content

.changeset/good-turtles-eat.md, packages/language-server/src/plugins/PluginHost.ts, packages/language-server/src/plugins/interfaces.ts, packages/language-server/src/plugins/typescript/TypeScriptPlugin.ts, packages/language-server/src/plugins/typescript/features/ReferencesProvider.ts, packages/language-server/src/plugins/typescript/features/TypeDefinitionsProvider.ts, packages/language-server/src/server.ts, packages/language-server/test/plugins/PluginHost.test.ts, packages/language-server/test/plugins/typescript/TypeScriptPlugin.test.ts, packages/language-server/test/plugins/typescript/features/ReferencesProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/references/frontmatter.astro, packages/language-server/test/plugins/typescript/fixtures/references/scriptTag.astro
Add support for Go to References / Find References. This was a bit confusing because there's multiple ways to do this and I'm not sure the differences between them 🤔
Like for https://github.com/withastro/language-tools/pull/416, this is only the Astro part of it. The TS part will be tackled when we update the TS plugin.
Added a test for this, added some tests that were missing from previous PRs
N/A
=> Add support for Go to References

.changeset/metal-bats-rhyme.md, packages/language-server/src/plugins/typescript/astro-sys.ts, packages/language-server/src/plugins/typescript/features/CompletionsProvider.ts, packages/language-server/test/plugins/typescript/features/CompletionsProvider.test.ts
My TS plugin explorations in https://github.com/withastro/language-tools/pull/427 made me realize that it was very easy to do this, so here it is
I do believe `readDirectory` is used for other things, but I couldn't find any issues when testing both through our tests and manually
Updated tests
N/A
=> Add support for import path completions for .md, .mdx and .html files

.changeset/nervous-fishes-unite.md, packages/language-server/src/plugins/astro/features/CompletionsProvider.ts, packages/language-server/test/plugins/astro/features/CompletionsProvider.test.ts, packages/language-server/test/plugins/astro/fixtures/completions/cssImport.astro
Previously when looking for the component import for props, we'd give up too early if we found an import with no clause (ex: `import 'thing.css'`), so we wouldn't properly get the type of the component. This fix that
Added test
N/A
=> Fix completions of component props not working if a CSS file was imported before the component

.changeset/mighty-teachers-sneeze.md, packages/language-server/src/plugins/typescript/features/CodeActionsProvider.ts, packages/language-server/test/plugins/typescript/features/CodeActionsProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/codeActions/onelineScriptTag.astro, packages/language-server/test/plugins/typescript/fixtures/codeActions/scriptTagImports.astro
In order to make them modules in TypeScript eyes, our script tags have some virtual code at the end. This does not cause issues in most cases, as we'll usually check to make sure positions are "in the real code" before doing anything. 
However, this doesn't always work for Organize Imports because it'll sometimes collapse code in a way where the beginning of the edit it gives is actually inside the real code, despite it mostly affecting virtual code. This goes both ways (edits to real imports will sometimes end in virtual code), so we can't check if both the start and the end of the edit is inside the real code without creating some situations where it wouldn't work
This PR works around this with our most reliable tool: `includes`.
Fix …
=> Fix Organize Imports adding virtual code to script tags

.changeset/lovely-kings-draw.md, packages/language-server/src/plugins/astro/AstroPlugin.ts
Previously we'd only load our own plugin when formatting, this PR make sure we also load other plugins. Notably, this fix compatibility with `prettier-plugin-tailwindcss`
N/A
=> Fix prettier plugins not being loaded when formatting

packages/language-server/package.json, packages/vscode/package.json, packages/vscode/scripts/build-node.js, pnpm-lock.yaml
I am not sure why, but when I started working on the extension today, despite having made absolutely no changes at all, I started getting weird errors that would crash the dev server. 
Logs were very cryptic which lead me to try a lot of things: Downgrade VS Code, Restart my computer, turn on and off macOS file indexing, update/downgrade dependencies etc. Nothing work, skimming through the bundled code where the error was, it seemed to be related to `synckit`. Reverting the TSX output (so also removing synckit) fixed it, so next thing I tried was going back to `main` and not bundling `synckit`, which fixes it. 
No idea what happened
N/A
=> fix(dev): Don't bundle Synckit to avoid weird issue

.github/workflows/ci.yml, .github/workflows/format.yml, .github/workflows/release.yml
Remove Node 14 in favor of [16, 18]. Also attempt to add macOS to see if it works now. Our minimum VS Code version has been a version with Node 16 for a long time now, so the only environnement running Node 14 were through `astro check`. Since Astro is looking toward dropping Node 14, so can we!
Fix https://github.com/withastro/language-tools/issues/270
We'll see! Re-ran the macOS CI three times to make sure the previous issue isn't there, seems like it doesn't happen anymore!
N/A
=> ci(node): Remove Node 14 from CI, Add Node 18

.changeset/chilly-points-sniff.md, packages/language-server/src/plugins/typescript/features/CompletionsProvider.ts
VS Code filters completions on the client, both to avoid the server doing unnecessary work and also because it believes it can do it better than the servers (which is true in most cases). One of the way it filters them is by excluding any completions whose replacement value is somewhere unrelated to where the completion was asked. 
As expected, this filtering happens while building the completion list, which in the case of languages that needs to be mapped, the positions of the completions also needs to be mapped, or VS Code just won't show them. Mapping the list isn't super expensive and only happens in certain cases, so it should mostly be fine. The most of the completion is still spent inside TS itself, so, there's bigger fishes to fry for sure. If it turns out to be a problem, there's …
=> fix(completions): Fix completions not showing up in VS Code in certain cases

.changeset/kind-flowers-rush.md, packages/vscode/package.json
Closes #477
Adds a `when` clause to the commands so that they are only shown when browsing `.astro` files - which matches the behavior of the TypeScript plugin.
TBD
bug fix only - no docs needed
=> add when-clause for commands

.changeset/tall-comics-give.md, packages/language-server/package.json, packages/ts-plugin/package.json, packages/vscode/package.json, pnpm-lock.yaml
This only upgrades the compiler version, I tried to use the sync entrypoint and the bundling was breaking in weird ways. It works in the Volar PR though, so not sure what's up there...
Also updated Prettier stuff while I was there, since the version was behind
CI should pass!
N/A
=> feat: upgrade compiler version

.changeset/happy-dancers-exist.md, .github/workflows/release.yml
**Blocked by the following compiler issue:**
- https://github.com/withastro/compiler/issues/714
and the release of the 1.0 of the Prettier plugin:
- https://github.com/withastro/prettier-plugin-astro/pull/329
---
After a few months in pre-release squashing bugs left and right and making sure everything is stable, it's time to cut an official 1.0 release of all the packages in this repo! 
There's still a lot of work to be done in the language server, both on bugs and on features, but we generally consider the current experience to be stable and featureful enough to release a 1.0 and start looking toward the future.
After this, you can expect the packages in this repo to follow semver and adhere more officially to the process the core Astro follow for releasing new versions.
N/A
N/A
=> 1.0 for the VS Code extension, the TypeScript plugin and the Astro language server

.changeset/modern-months-stare.md, packages/language-server/src/plugins/typescript/language-service.ts
Closes https://github.com/withastro/language-tools/issues/526
The [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration) dictates that the `workspace/configuration` method request contains a `scopeUri` which should be of type `DocumentUri`. This request was sometimes being sent with a path instead.
Bugfix, not sure how to test
No documentation update necessary
=> Fix `workspace/configuration` request parameter type

.changeset/late-coins-tan.md, packages/ts-plugin/src/index.ts, packages/ts-plugin/src/language-service/index.ts, packages/ts-plugin/src/module-loader.ts, packages/ts-plugin/src/utils.ts
Our plugin was broken in TS 5.0+ due to internal changes to TS. This PR fixes this by using the recommended method for patching language services inside TypeScript plugins and patching the right method for resolving modules
Fix https://github.com/withastro/language-tools/issues/519
Tests should pass!
N/A
=> fix: Fix TypeScript plugin compatibility with TS 5.0

.changeset/happy-geese-invent.md, packages/vscode/src/client.ts
Regarding the configuration of `astro.trace.server`. 
https://github.com/withastro/language-tools/blob/eb2ce0b3effd00e49294be57ef0f3d1cb5f8f454/packages/vscode/package.json#L141
I have made modifications because there seems to be a difference between the configured LanguageClient.id and the actual behavior.
https://github.com/withastro/language-tools/blob/eb2ce0b3effd00e49294be57ef0f3d1cb5f8f454/packages/vscode/src/client.ts#L69
None
None
=> fix: changed the LanguageClient.id because trace.server is not working

.changeset/lazy-wolves-leave.md, packages/language-server/src/core/utils.ts
=> fix: crash with files with characters that can't be expressed with valid characters for TSX identifiers

.github/workflows/congrats.yml
Adds a workflow that uses our CongratsBot action to post to `#dev-tooling` on Discord.
Picks from the following emoji to open the message:
Worked so far in other repos 🤞 
N/A
=> Add a congrats bot workflow that posts to Discord

.changeset/friendly-games-tease.md, packages/language-server/src/core/parseJS.ts
Much like hoisted script tags, script tags with `type="module"` should be treated as their own scope, so variables don't leak out to inline scripts
N/A
=> Treat `type="module"` script tags as their own scope

.github/workflows/congrats.yml
Adds a condition to the congrats bot CI job, which causes the job to be skipped if the commit message is `[ci] format`.
Same logic as in https://github.com/withastro/astro/blob/cc8e9de88179d2ed4b70980c60b41448db393429/.github/workflows/main.yml#L20
N/A.
=> Don’t congratulate the formatter 😠

.changeset/five-rings-explode.md, packages/language-server/src/importPackage.ts, packages/language-server/src/languageServerPlugin.ts, packages/language-server/test/misc/format.test.ts, packages/language-server/test/server.ts
`getPackagePath` returns the root of the package (since that's what we want for editor integrations), however since Prettier plugins are now ESM, what we need is the specific file to import, so this fix that
Fix https://github.com/withastro/language-tools/issues/616
I added a test 
N/A
=> fix(formatting): Fix Prettier not importing the right file when formatting 

.changeset/pink-geese-design.md, packages/language-server/src/plugins/typescript/completions.ts, packages/language-server/test/typescript/completions.test.ts
What the title says. Also a small fix to other completions to make sure their normal sorting order is still considered while sorting, despite being sorted higher. I'm not sure if it matters in VS Code, but other editors might use the full sorting text more
Added a test
N/A
=> feat(completions): Order `astro:` completions higher

.changeset/lazy-pugs-melt.md, packages/language-server/package.json
Bump peer dep range to support prettier-plugin-astro 0.12. Encountered this while bumping deps in core.
Ran formatting and checks in core with 0.12 and it works.
n/a. bump range only.
=> Support prettier-plugin-astro v0.12 in language-server

.changeset/new-goats-lie.md, packages/ts-plugin/src/index.ts
Workaround for an upstream bug in TypeScript
Fix https://github.com/withastro/language-tools/issues/622
Fix https://github.com/withastro/language-tools/issues/614
I'm... not sure how to test this. We have some tests for the TypeScript plugin, and they still pass. I was never able to reproduce any crashes in local, so. I ran around a repo using `moduleResolution: 'bundler'` and everything seemed to work.
N/A
=> Fix TypeScript plugin crash

.changeset/tiny-paws-design.md, packages/language-server/src/languageServerPlugin.ts
I added that option myself to Volar and then promptly forgot to use it here. Derp.
Fix https://github.com/withastro/language-tools/issues/635
Tested manually, testing formatting settings is only vaguely possible in the monorepo because Prettier tends to find the monorepo's formatting config
N/A
=> Use editor formatting settings as fallback when there's no Prettier config

.changeset/lazy-dodos-mate.md, package.json, packages/astro-check/package.json, packages/astro-check/test/check.test.ts, packages/language-server/src/check.ts, packages/ts-plugin/test/suite/extension.test.js
The check entrypoint of the language-server would still try to print something even though there was no errors in the file, this resulted in sometimes some newlines showing when they shouldn't
Fixed some test logic that passed by accident, oops
N/A
=> Fix `astro check` printing newlines by accident

.changeset/cold-llamas-compare.md, packages/language-server/src/core/parseCSS.ts, packages/language-server/src/core/parseJS.ts, packages/language-server/test/units/parseCSS.test.ts, packages/language-server/test/units/parseJS.test.ts
The `language-server` only embedded `<script>`&`<style>` tags on root level. This PR adds recursion on extracting/embedding all `<script>`&`<style>` tags from the `htmlDocument`. Using `.children` recursively.
Added tests. Additionally, the change was tested by nesting multiple `<div>`'s and then trying to autocomplete in an `<script>` or `<style>` tag. I didn't find any relevant tests for that sort of case, if wanted I could add one.
bug fix only
=> fix(parser): nested <script> tags are not extracted

.changeset/chilly-pigs-design.md, package.json, packages/astro-check/package.json, packages/language-server/package.json, packages/ts-plugin/package.json, packages/vscode/package.json, packages/vscode/scripts/build.mjs, pnpm-lock.yaml
Update Volar and VSCode deps.
There are two changes to note.
1. VSCode extension required from 1.67.0 to 1.82.0.
2. `"overrides": { "@astrojs/language-server": "file:./packages/language-server" }` added to root package.json to avoid introducing different language server versions.
=> chore: update volar and vscode deps

.changeset/cool-pumpkins-invent.md, .gitignore, packages/language-server/src/core/parseJS.ts, packages/language-server/test/units/parseJS.test.ts
Fix #513
- `parseJS` will now ignore JSON scripts, including both MIME JSON types and `importmap` and `speculationrules` script types
- Add a test "Ignore JSON scripts" in `packages/language-server/test/units/parseJS.test.ts`
N/A
=> parseJS will now ignore JSON scripts 

.changeset/hot-months-promise.md, packages/language-server/src/languageServerPlugin.ts
fix #668
One line fix : in `packages/language-server/src/languageServerPlugin.ts`, `resolvedConfig` overwrite our plugins array.
Module not tested.
N/A.
=> Prettier: fix usage of plugins without prettier-plugin-astro

.changeset/late-horses-call.md, CONTRIBUTING.md, packages/language-server/src/importPackage.ts
Just a small thing. Editor integrations from Vue and Svelte can fail to load sometimes, previously we'd just output a generic message when we can show the entire error. This prevented users from debugging https://github.com/withastro/language-tools/issues/652 on their end
N/A
N/A
=> feat: add full reason for editor integration failing to load

.changeset/chilly-bananas-repeat.md, packages/language-server/src/core/parseJS.ts, packages/language-server/test/units/parseJS.test.ts
Formatting was wrongly enabled inside inline script tags capabilities, we don't want formatting on virtual files because Prettier handles the entire `.astro` file itself
Added a test
N/A
=> fix: formatting messing up inline scripts

.changeset/popular-shirts-fix.md, packages/language-server/src/check.ts
When you use `astro check --minimumSeverity error`, it's supposed to filter logs based on the severity level, but it's showing all logs, regardless of this setting. 
I've tweaked it so that the default is now `hint`, which keeps things as they were. But when you set `--minimumSeverity error`, it'll only show the logs that are errors, just like you'd expect.
There aren't any automated tests for this feature yet, so I just tested this manually.
This update is more about fixing the behavior to match what we say in the `--help` output, and I didn't find any specific documentation that needs updating for this.
=> Fix ignored minimal severity flag

.changeset/rich-adults-sparkle.md, packages/language-server/src/check.ts, packages/language-server/src/languageServerPlugin.ts, packages/language-server/src/utils.ts
Improve the Astro detection to only attempt to find Astro in relevant contexts and better handle incomplete packages
Fix https://github.com/withastro/language-tools/issues/704
Fix https://github.com/withastro/language-tools/issues/644 (as far as I could tell? I tried reproducing it in both npm and pnpm and couldn't, everything worked perfectly fine.)
Tested manually, we can't really test this in the monorepo because `astro` is a devDep of some things and so resolution isn't really accurate compared to a normal Astro project.
N/A
=> fix: improve Astro detection to avoid false warnings

.changeset/early-fireants-leave.md, packages/language-server/src/core/parseJS.ts
- Closes #711
<details>
<summary>Manually tested against this snippet:</summary>
```astro
---
export interface Props {
server: string;
}
const { server } = Astro.props;
---
<div id="waline"></div>
<script>
import { init } from "https://unpkg.com/@waline/client@v2/dist/waline.mjs";
const x = 43
init({
el: "#waline",
serverURL,
});
</script>
<script define:vars={{ serverURL: server }} type="module">
import { init } from "https://unpkg.com/@waline/client@v2/dist/waline.mjs";
const x = 42
init({
el: "#waline",
serverURL,
});
</script>
<script is:inline>
const x = 43
</script>
<script is:inline>
const x = 44
</script>
```
</details>
Does not affect usage
=> Prevent type checking `define:vars` scripts

.changeset/curly-rabbits-rush.md, packages/language-server/src/core/astro2tsx.ts, packages/language-server/src/core/index.ts, packages/language-server/src/core/parseAstro.ts, packages/language-server/test/units/parseAstro.test.ts, packages/language-server/test/units/parseCSS.test.ts, packages/language-server/test/units/parseJS.test.ts, packages/language-server/test/units/utils.test.ts, packages/vscode/syntaxes/astro.tmLanguage.json
Fix https://github.com/withastro/language-tools/issues/702
Fix https://github.com/withastro/language-tools/issues/698
Fix https://github.com/withastro/language-tools/issues/623
To be clear, it doesn't fix those issues upstream, it just prevents the language server from crashing when those issues happens. We'll be tracking the status of those upstream, as having duplicate issues in both repos has resulted in inefficiencies in our processes
N/A
=> fix(ast): Don't crash language-server if the compiler fails to parse a file

.changeset/hungry-toes-cover.md, .eslintignore, packages/language-server/src/plugins/typescript/diagnostics.ts, packages/language-server/src/plugins/typescript/index.ts, packages/language-server/test/check/check.test.ts, packages/language-server/test/check/fixture/tsFileWithErrors.ts, packages/ts-plugin/test/runTest.js, packages/vscode/test/runTest.js
We were wrongly returning `null` for diagnostics when the current file isn't an Astro file. In the editor, this is kinda fine, but in `astro check` this meant that errors in `.ts` files could be ignored. This only affects semantic diagnostics, as we don't process other ones.
Added a TypeScript file to the `astro check` fixture
N/A
=> fix(check): Fix TypeScript files not being properly checked by `astro check`

.changeset/famous-panthers-carry.md, packages/vscode/languages/astro-language-configuration.json
We weren't allowing autoclosing before `<`, so inside tags sometimes it didn't work.
Fix https://github.com/withastro/language-tools/issues/703
N/A
=> fix(syntax): Fix autoclosing not working inside of tags sometimes

.changeset/chatty-dolls-itch.md, packages/language-server/src/core/parseJS.ts
What the title says! This is not perfect, but then again, it's not perfect in VS Code's HTML support either:
If this is enough for VS Code, it's enough for me. At least, for now.
Fix https://github.com/withastro/language-tools/issues/587
N/A
=> fix(parseJS): Suffix inline attributes with a semicolon to avoid errors leaking

.changeset/tricky-wasps-check.md, packages/language-server/src/check.ts
=> fix: temporarily disable checking `.js(x)` files

.changeset/hot-donuts-beg.md, packages/vscode/syntaxes/astro.tmLanguage.json, packages/vscode/syntaxes/astro.tmLanguage.src.yaml, packages/vscode/test/grammar/fixtures/attributes.astro, packages/vscode/test/grammar/fixtures/attributes.astro.snap
This turns escaped interpolations from
To 
- Added a snapshot test
N/A bug fix
=> Fix incorrectly highlighted escaped interpolation in template literal attributes

.changeset/mighty-mayflies-tell.md, packages/language-server/src/check.ts
We were wrongfully including Svelte and Vue in the list of files to check by `astro check`. Since we don't really have a proper understanding of those files (we mostly fake understanding them, especially Vue), we can't check them ourselves and shouldn't be trying to.
WIP
N/A
=> fix(check): Skip Vue and Svelte files

.changeset/smart-cycles-join.md, packages/language-server/src/plugins/astro.ts
For compiler warnings, the visual markers were also displayed on some characters in the following line. Maybe I misunderstood something here, but I fixed it to the best of my knowledge :)
Manually tested.
There are test for Compiler Points but those functions seem to be outdated not to be in use anywhere?
n.a., bug fix
=> map compiler location to LSP range

.changeset/chilled-adults-invite.md, packages/language-server/src/check.ts
`astro check` has an `--tsconfig` option that takes a file parameter.
Now it also understands relative file names.
Manually tested
bugfix / n.a.
=> Makes astro check --tsconfig understand relative file names

.eslintrc.cjs, biome.json, package.json, packages/astro-check/package.json, packages/language-server/package.json, packages/ts-plugin/package.json, packages/vscode/package.json, pnpm-lock.yaml
- Updated `biome` to the latest.
- `biome` now formats `package.json` files. Happy to revert the changes. They are different from prettier because prettier just format them with `JSON.strigify(content, null, 2)`.
- I removed the eslint prettier packages because they aren't needed anymore.
- Biome now handles Astro and Svelte files, with some limitations. For example the indentation in the svelte file is different (and expected). Happy to revert it if not wanted.
The CI should still pass
=> chore: update biome

.changeset/wet-beers-change.md, packages/vscode/syntaxes/astro.tmLanguage.json, packages/vscode/syntaxes/astro.tmLanguage.src.yaml, packages/vscode/test/grammar/fixtures/text.astro, packages/vscode/test/grammar/fixtures/text.astro.snap
In this case : 
```jsx
blabla<div>word</div>
{true && <div>word</div>}blabla
```
Both `blabla` have the scope `source.astro` instead of `text.astro`, which is the scope in HTML. Fixed the `text.astro` pattern to match that.
Snap test -> `packages/vscode/test/grammar/fixtures/text.astro.snap`
N/A, this PR will match the documented behaviour.
=> fix `tmLanguage`: text.astro pattern

.changeset/two-worms-cover.md, packages/vscode/syntaxes/astro.tmLanguage.json, packages/vscode/syntaxes/astro.tmLanguage.src.yaml, packages/vscode/test/grammar/fixtures/text.astro, packages/vscode/test/grammar/fixtures/text.astro.snap
- Fix regression from #826 , breaking frontmatter highlighting in `.astro` files
- Create a `text` pattern after `scope` & `frontmatter` patterns, so it only match what's left
- Add a better text & frontmatter snap test
N/A, this PR try to match the documented behaviour.
=> refactor(tmLanguage): text pattern

.changeset/rotten-poets-repeat.md, packages/language-server/src/plugins/typescript/codeActions.ts, packages/language-server/src/plugins/typescript/completions.ts, packages/language-server/src/plugins/typescript/utils.ts, packages/language-server/test/fixture/env.d.ts, packages/language-server/test/fixture/scriptImport.astro, packages/language-server/test/typescript/completions.test.ts
In some cases, we were wrongly trying to map text edits inside script tags as if they were in the template, this PR fixes this. This mostly affects completions.
Fixes https://github.com/withastro/language-tools/issues/805
Added a test!
N/A
=> fix: Fixes text edits inside script tags not being mapped correctly

.changeset/thirty-peas-turn.md, packages/language-server/src/plugins/html.ts, packages/language-server/test/html/custom-data.test.ts
The API for loading custom data changed, but we didn't have a test for custom data, only normal completions. This makes it so we use the proper API now.
Fixes https://github.com/withastro/language-tools/issues/840
Added a test!
N/A
=> fix(html): Load custom data the proper way

.changeset/forty-flowers-drum.md, packages/vscode/package.json, packages/vscode/test/grammar/test.mjs
Add a few more things from TSX's syntax to our rules that are not inherited due to a VS Code bug. 
Fixes https://github.com/withastro/language-tools/issues/713 and a few unreported issues (ex: `>>>=` wasn't properly highlighted
Tested manually, you can't test this inside grammar tests because you don't see the underlying language being applied, just the `source.tsx` scope.
N/A
=> fix(syntax): Apply JSX latest rules for our language

.changeset/eleven-pears-switch.md, packages/language-server/src/core/svelte.ts, packages/language-server/src/core/utils.ts, packages/language-server/src/core/vue.ts
We wrongfully had mappings for Vue and Svelte files, so when we updated files, we could sometimes try to update Svelte and Vue files, but really, we don't know what to do there, so we shouldn't.
Fixes https://github.com/withastro/language-tools/issues/869
Tested manually, this is quite tough to test in the testing suite because we can't quite mock what the client does
N/A
=> fix: don't generate mappings for Svelte and Vue files

.changeset/friendly-jars-cover.md, packages/astro-check/README.md, packages/astro-check/package.json
- Adds a README to the `@astrojs/check` package similar to the ones we use for Astro integrations (inspired by someone who found the package on npm and didn’t know what it was)
- Adds `description` and `homepage` fields to `package.json` too
n/a metadata change only
It’s all docs I guess.
=> Add `@astrojs/check` README

.changeset/warm-lemons-search.md, packages/vscode/package.json, packages/vscode/syntaxes/mdx.astro.tmLanguage.json
This adds support for syntax highlighting `astro` tagged code blocks inside MDX files.
````mdx
This is MDX
```astro
---
const frontmatter = 'This is Astro frontmatter'
---
<div>This is an Astro template</div>
```
````
With the [MDX extension](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx) installed, open the Astro language tools repo and create an Astro code block inside an MDX file.
I don’t know what documentation would be needed for this.
=> feat: highlight Astro code blocks in MDX

.changeset/light-bananas-fail.md, packages/language-server/package.json, packages/language-server/src/core/astro2tsx.ts, packages/language-server/src/core/index.ts, packages/language-server/src/core/parseCSS.ts, packages/language-server/src/core/parseJS.ts, packages/language-server/test/css/completions.test.ts, packages/language-server/test/typescript/completions.test.ts, packages/language-server/test/units/parseCSS.test.ts, packages/language-server/test/units/parseJS.test.ts, packages/vscode/package.json, pnpm-lock.yaml
Requires https://github.com/withastro/compiler/pull/1019
This PR reworks how script and style are extracted from files, using the compiler's information instead of crawling through various ASTs. This makes file updates simpler, much faster, and also more correct as the ASTs sometimes had wrong or misleading positions due to how they were being generated.
Fixes https://github.com/withastro/language-tools/issues/800
Fixes https://github.com/withastro/language-tools/issues/862
This PR also fixes an issue where CSS selection ranges didn't work inside style tags, reported on Discord
Tests should pass!
N/A
=> fix: scripts affecting intellisense

.changeset/smooth-ravens-visit.md, packages/language-server/src/core/astro2tsx.ts, packages/language-server/test/typescript/scripts.test.ts
I'm just dumb, I forgot to turn on the new flag I added 🤦‍♀️
Added tests that would've covered this. The reason it got through is because the current tests tested that the features (completions, diagnostics etc) works in script tags and that the extraction was done properly (which both are true). However, the errors only happened in actual "end to end" situation where the diagnostics from TSX and the extracted script tags are merged, which wasn't covered (well it was, but separately). Anyway, it's covered now
N/A
=> Fixes script and style tags being wrongfully included in the generated TSX

.changeset/ten-adults-sparkle.md, packages/language-server/src/languageServerPlugin.ts
By forcing JSX mode on Emmet instead of HTML, we don't get the useless completions inside expressions. I'm not sure 100% what else it changes, as it's not documented, but reading through Emmet's source code I couldn't find anything too bad.
Close https://github.com/withastro/language-tools/discussions/835
For some reason, I can't seem to be able to get emmet completions in the tests. I remember something similar happening in the previous language-server as well, I'm not too sure why that happens!
N/A
=> feat: put emmet in JSX mode to avoid expressions completions

.github/ISSUE_TEMPLATE/---01-bug-report.yml
Add text input to bug issue template for providing link to reproduction
- adds new required input for providing a link to a reproduction to the bug issue template 
- checked rendered template in fork (see screenshot)
- update to issue template only
=> Update bug issue template

.changeset/wet-kangaroos-hide.md, packages/language-server/package.json, packages/language-server/src/core/index.ts, packages/language-server/src/core/parseCSS.ts, packages/language-server/src/core/parseJS.ts, packages/language-server/test/css/completions.test.ts, packages/language-server/test/typescript/scripts.test.ts, packages/language-server/test/units/parseJS.test.ts, packages/ts-plugin/package.json, packages/vscode/package.json, pnpm-lock.yaml
> Require https://github.com/withastro/compiler/pull/1032
A long time ago (before the port to Volar), this was actually supported, but we lost it without noticing. This PR adds it back.
Fixes https://github.com/withastro/language-tools/issues/916
Added tests
N/A
=> Adds support for SCSS and LESS intellisense inside style tags

.changeset/tame-balloons-type.md, packages/language-server/src/plugins/astro.ts, packages/language-server/test/astro/codelens.test.ts
Following the amazing TBD call you and Ema gave, I discovered the existence of the `Astro.glob` CodeLens and as it was not working, I decided to fix it.
Before this change, the `Astro.glob` CodeLens was not being displayed:
After this change, the `Astro.glob` CodeLens is now displayed:
To give a bit more context to the change, the `document.uri` in `provideCodeLenses()` was the one of a Volar embedded document so calling `getSourceFile()` on the TS program with it was returning `undefined`. To fix this, I decode the embedded document URI to get the original file URI, and use its `fsPath` to get the source file and also to get the directory name to get the glob result.
To get the CodeLens to show, I only needed `"editor.codeLens": true` in my Visual Studio Code settings.
So this is the …
=> Fix `Astro.glob` CodeLens

packages/astro-check/package.json, pnpm-lock.yaml
I don't think it matters in practice since `fast-glob` is also used by astro and language-server, but this helps keep the exact deps used concise.
existing tests should pass
n/a
=> chore(astro-check): remove unused fast-glob dep

.changeset/lazy-masks-behave.md, packages/language-server/src/core/frontmatterHolders.ts, packages/ts-plugin/src/frontmatter.ts, packages/vscode/src/client.ts
- changes mdoc language identifier from `mdoc` to `markdoc`
- existing tests
- bugfix
=> fix: mdoc language identifier

.changeset/giant-pots-bathe.md, packages/astro-check/package.json, packages/astro-check/src/index.ts, pnpm-lock.yaml
Upgrade chokidar to v4.
Tested on a separate repo to make sure `astro check --watch` still works
n/a. added a changeset in case the chokidar upgrade could affect someone, but i think it shouldn't.
=> chore: upgrade chokidar

.changeset/long-dolphins-glow.md, packages/language-server/src/plugins/typescript/index.ts, packages/language-server/test/fixture/renameThis.ts, packages/language-server/test/fixture/renaming.astro, packages/language-server/test/server.ts, packages/language-server/test/typescript/renames.test.ts, packages/vscode/package.json
When using the Astro TypeScript plugin in addition to the language server, both will attempt to update imports whenever a file is renamed. 
Both of them will handle it correctly individually, however if you run both in a row (pressing Yes or Always to the prompt in VS Code) the result will be corrupted, as editors who can handle multiple LSP renaming at the same time won't merge the results, they'll run them sequentially.
This PR adds a setting to disable the language server's handling of this, as more often than not, you want the TS plugin to handle it (so that it might handle additional formats from other plugins as well). This setting is disabled by default in VS Code, as the TS plugin is always included.
Fix https://github.com/withastro/language-tools/issues/896
Added tests
Apart from …
=> feat: allow disabling handling updating files on file renames

.changeset/empty-crabs-destroy.md, packages/language-server/src/core/frontmatterHolders.ts, packages/language-server/src/languageServerPlugin.ts, packages/language-server/src/nodeServer.ts, packages/language-server/src/plugins/yaml.ts, packages/language-server/test/content-intellisense/caching.test.ts, packages/language-server/test/fixture/src/content/caching/caching.md, packages/language-server/test/fixture/src/content/config.ts, packages/language-server/test/typescript/caching.test.ts, packages/language-server/test/typescript/completions.test.ts, packages/language-server/test/typescript/renames.test.ts, packages/language-server/test/utils.ts, packages/ts-plugin/src/frontmatter.ts, packages/vscode/src/client.ts
This reworks a bit how we handle reloading schemas and add support for reloading the entire collections config. This PR focuses on fixing the language server handling of it, the TypeScript plugin part isn't as problematic, the only thing it doesn't handle is new collections being added, file updates works correctly (since they only care about the .ts part, not the schema)
I added a (1) test, this is generally hard to test because there's so many moving parts to it, the editor seeing the file changes, Astro reloading the file etc. 
The one test should at least make sure the general idea for updating schemas works
N/A
=> fix: reload content on collections change

.changeset/tricky-coins-hammer.md, packages/language-server/src/plugins/typescript-addons/snippets.ts
Astro 4.14 removed the option for dynamic prerendering. This removes the editor hint that you can do it.
Not tested. Trusted Erika.
No docs; only updates editor hover text.
=> remove `import.meta.env` as an option for export const prerender
