.github/workflows/release.yml
Adds NPM_TOKEN to our release action
=> Include the NPM_TOKEN

.changeset/wild-cameras-poke.md, packages/language-server/src/plugins/typescript/astro2tsx.ts
=> Remove diagnostic error for the doctype

.changeset/breezy-buckets-shop.md, packages/language-server/astro.d.ts
=> Add Astro.resolve to the Astro global type defs

.changeset/friendly-masks-confess.md, packages/language-server/astro.d.ts, packages/language-server/test/diagnostics/fragment.mjs
- Adds type info for `Fragment` to prevent errors.
=> Allow fragments

.changeset/rich-kangaroos-pull.md, packages/language-server/package.json
- Missing deps found in an audit
N/A
N/A
=> Add missing language server deps

.changeset/early-frogs-draw.md, packages/vscode/syntaxes/astro.tmLanguage.json
- Fixes an issue where `<style>` would be matched as a `<script>`.
syntax fix only
syntax fix only
=> Fix plain script and style blocks

.changeset/soft-pens-glow.md, .github/workflows/ci.yml, packages/language-server/test/diagnostics/at-prefixed-attribute.mjs, packages/language-server/test/diagnostics/fragment.mjs, packages/language-server/test/diagnostics/multiple-comments.mjs, packages/language-server/test/diagnostics/slots.mjs, packages/language-server/tsconfig.json
- Updates tests to run on Node v12
- Updates tsconfig to support node v12
- Updates CI to also test Node v12
- Fixes the new Astro smoke test: https://github.com/withastro/astro/runs/4480411520?check_suite_focus=true
- tested!
- N/A
=> Add Node v12 support

.changeset/modern-actors-roll.md
- adds changeset for https://github.com/withastro/language-tools/pull/151
changeset only
changeset only
=> add changeset for vite client types

README.md
Update the sponsors in the README to match the main repo, StackUp was missing in this repo
No testing needed
No docs needed
=> Update sponsors in README

.changeset/fuzzy-knives-poke.md, .github/workflows/release.yml
- Re-enables the OpenVSX publishing as I have been granted the astro-build namespace.
- Closes #16 
N/A
N/A
=> Enable publishing to OpenVSX

packages/language-server/src/plugins/typescript/language-service.ts, packages/language-server/types/astro-jsx.d.ts
Add a few missing properties, fix name casing of SVG properties
No docs needed
=> Misc TSX typing fixes

.github/workflows/ci.yml, packages/language-server/test/plugins/typescript/features/CodeActionsProvider.test.ts, packages/language-server/test/plugins/typescript/features/CompletionsProvider.test.ts, packages/language-server/test/plugins/typescript/features/DiagnosticsProvider.test.ts, packages/language-server/test/plugins/typescript/features/FoldingRangesProvider.test.ts, packages/language-server/test/utils.ts
Previously we only tested Ubuntu in CI. This makes it so tests are also run on Windows and macOS
Well.. It's tests...
No docs needed
=> Run tests on Windows in CI

.changeset/angry-starfishes-brake.md, packages/vscode/README.md, packages/vscode/package.json, yarn.lock
Update our README with more updated info on supported features and some commonly missed info (ex: how to change the formatting settings)
Also updated our marketplace page with some tags and proper categories to improve discovery
N/A
I guess it's technically docs
=> Update VS Code README and marketplace page

README.md
**This PR should be merged _AFTER_** https://github.com/withastro/.github/pull/2
- This PR updates a link to the GOVERNANCE file which will move once https://github.com/withastro/.github/pull/2 is merged
n/a
n/a
=> Update link to GOVERNANCE.md

.changeset/lovely-items-rule.md, packages/vscode/syntaxes/astro.tmLanguage.json, packages/vscode/test/grammar/fixtures/attributes.astro, packages/vscode/test/grammar/fixtures/attributes.astro.snap
Update our syntax file to support @_. as valid characters in attribute names
Added test
N/A
=> Add support for @_. in attribute names to syntax highlight

.changeset/dry-peas-perform.md, packages/language-server/src/plugins/PluginHost.ts, packages/language-server/src/plugins/interfaces.ts, packages/language-server/src/plugins/typescript/TypeScriptPlugin.ts, packages/language-server/src/plugins/typescript/features/TypeDefinitionsProvider.ts, packages/language-server/src/server.ts, packages/language-server/test/plugins/typescript/features/TypeDefinitionsProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/tsconfig.json, packages/language-server/test/plugins/typescript/fixtures/typeDefinitions/otherFile.astro, packages/language-server/test/plugins/typescript/fixtures/typeDefinitions/sameFile.astro, packages/language-server/test/plugins/typescript/fixtures/typeDefinitions/script.ts, packages/language-server/test/plugins/typescript/fixtures/typeDefinitions/scriptTag.astro
Adds support for Go To Type Definition. Code is really similar to Go To Definition, some things are just slightly differently named
Close https://github.com/withastro/language-tools/issues/310
Added tests
N/A
=> Add support for Go to Type Definition

.changeset/large-wolves-work.md, packages/language-server/src/check.ts, packages/language-server/test/check.test.ts, packages/language-server/test/fixtures/astro-check/hasError.astro, packages/language-server/test/utils.ts
We were running the checker init before loading TypeScript, oops
Added a test for astro check
N/A
=> Fix astro check initializing before TypeScript was loaded

.github/workflows/format.yml, package.json, pnpm-lock.yaml
Add a format workflow thingy so the repo is automatically formatted and imports organized, just like the main repo has
N/A
N/A
=> Add Format workflow to autoformat like the main repo does

.changeset/mighty-doors-swim.md, packages/vscode/syntaxes/astro.tmLanguage.json, packages/vscode/test/grammar/fixtures/attributes.astro, packages/vscode/test/grammar/fixtures/attributes.astro.snap
Numbers were not included in the regex, now they are!
Added test
N/A
=> Fix numbers not being highlighted properly inside HTML attributes

.changeset/brown-berries-destroy.md, packages/language-server/package.json, packages/ts-plugin/package.json, packages/vscode/package.json, pnpm-lock.yaml
- Upgrades `@astrojs/compiler` to latest
- Fixes issues outlined in https://github.com/withastro/compiler/issues/631
N/A, already covered
N/A, dep bump
=> chore: upgrade compiler

packages/language-server/package.json, packages/ts-plugin/package.json, packages/vscode/package.json, pnpm-lock.yaml
Just update the compiler version with latest fixes
We'll see!
N/A
=> chore(deps): Upgrade compiler

.changeset/old-humans-thank.md, packages/vscode/package.json
This enables breakpoints inside Astro files, simple change. From my tests, it seems like they're not mapped correctly necessarily, but I don't think this is something we can control from the extension pov
Fix https://github.com/withastro/language-tools/issues/468
N/A
N/A
=> feat(debugging): Add support for breakpoints inside Astro files

.changeset/mean-laws-work.md, packages/language-server/package.json, packages/language-server/src/core/worker/TSXService.ts, packages/language-server/src/plugins/PluginHost.ts, packages/language-server/src/plugins/astro/features/DiagnosticsProvider.ts, packages/language-server/src/plugins/css/CSSPlugin.ts, packages/language-server/src/plugins/html/HTMLPlugin.ts, packages/language-server/src/plugins/typescript/TypeScriptPlugin.ts, packages/language-server/src/plugins/typescript/astro2tsx.ts, packages/language-server/src/plugins/typescript/features/DiagnosticsProvider.ts, packages/language-server/src/plugins/typescript/features/RenameProvider.ts, packages/language-server/src/plugins/typescript/snapshots/DocumentSnapshot.ts, packages/language-server/src/server.ts, packages/language-server/test/plugins/css/CSSPlugin.test.ts, packages/language-server/test/plugins/html/HTMLPlugin.test.ts, packages/language-server/test/plugins/typescript/features/RenameProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/renaming/crossFile.astro, packages/language-server/test/plugins/typescript/fixtures/renaming/script.ts, packages/language-server/test/plugins/typescript/fixtures/renaming/simple.astro, packages/ts-plugin/src/astro2tsx.ts, packages/ts-plugin/src/workers/TSXService.ts, pnpm-lock.yaml
Title is self explanatory! We had renaming support already, but it wasn't always quite working, especially on Windows
Fix https://github.com/withastro/language-tools/issues/368
Added tests for it
N/A
=> Add support for renaming

.changeset/tender-flies-cheer.md, packages/language-server/src/plugins/typescript/features/DiagnosticsProvider.ts, packages/language-server/test/plugins/typescript/features/DiagnosticsProvider.test.ts, packages/language-server/test/plugins/typescript/fixtures/diagnostics/contentcollections.astro, packages/ts-plugin/src/language-service/diagnostics.ts
Does what the title says!
Added a test for the language-server part, not sure how to test the ts plugin on this (as always 😔)
N/A
=> Add an error message explaining how to generate types for content collections

.changeset/six-peaches-beg.md, packages/language-server/package.json, packages/language-server/src/core/worker/TSXService.ts, packages/language-server/src/plugins/typescript/astro2tsx.ts, packages/language-server/test/plugins/astro/features/DiagnosticsProvider.test.ts, packages/language-server/test/plugins/astro/fixtures/diagnostics/compilerError.astro, packages/ts-plugin/package.json, packages/ts-plugin/src/astro2tsx.ts, packages/ts-plugin/src/workers/TSXService.ts, packages/vscode/package.json, pnpm-lock.yaml
Upgrade the compiler version with multiple fixes
We'll see!
NA/
=> chore: compiler upgrade

packages/language-server/package.json, packages/ts-plugin/package.json
Add repository field in package.json file
=> chore: add repository in package.json

.changeset/witty-yaks-lick.md, packages/language-server/src/plugins/html-data.ts
- Specifies `transition:name` and `transition:animate`
I did not :( Should I have?
N/A
=> Adds transition:name and transition:animate attributes

.github/workflows/ci.yml, .github/workflows/format.yml
CI was still on old versions of Node. This PR also makes it so we use the standard format task
We'll see!
N/A
=> feat: run CI on latest Node versions

.changeset/big-glasses-beg.md, packages/language-server/src/check.ts
With the JSX typing issue now fixed, we can remove the hotfix!
N/A
N/A
=> feat: remove astro check hotfix

.changeset/fair-knives-think.md, packages/language-server/src/plugins/html-data.ts
=> Adds an entry for transition:persist

README.md
The current URL is returning 404
=> Fixed volarjs URL

packages/language-server/package.json, packages/language-server/test/check/check.test.ts, packages/language-server/test/check/fixture/frameworks/Component.svelte, packages/language-server/test/check/fixture/frameworks/Component.vue, packages/language-server/test/check/fixture/frameworks/frameworks.astro, packages/language-server/test/typescript/diagnostics.test.ts, pnpm-lock.yaml
Attempting to diagnose the Svelte and Vue issues
=> test: add tests for Svelte and Vue inside `astro check`

.changeset/smooth-boxes-yawn.md, packages/language-server/src/core/index.ts, packages/language-server/src/core/svelte.ts, packages/language-server/src/core/vue.ts, packages/language-server/src/importPackage.ts, packages/ts-plugin/src/astro2tsx.ts, packages/ts-plugin/src/index.ts, packages/ts-plugin/src/language.ts
=> fix: decode `fileId`

.changeset/young-countries-hide.md, packages/language-server/src/plugins/html-data.ts
- As I was perusing the code, I found some descriptions that might be improved/formatted. I hope this is an okay first PR!
- I added periods to the end of every description, as some already had periods and the MDN editor docs also have periods at the end.
Tests pass, none added because this modifies previously added descriptions and no tests failed.
Formatting and aesthetic DX fix only.
=> Format/improve descriptions for Astro attributes

.changeset/few-ducks-explain.md, packages/language-server/src/plugins/html-data.ts
Adds autocomplete for `data-astro-rerun` to scripts
YOLO, but I'm more than happy to do some if guidance can be provided
https://github.com/withastro/docs/pull/6798
https://github.com/withastro/astro/pull/9977
=> add data-astro-rerun to scripts

.changeset/old-apes-beg.md, packages/vscode/syntaxes/astro.tmLanguage.json, packages/vscode/syntaxes/astro.tmLanguage.src.yaml, packages/vscode/test/grammar/fixtures/attributes.astro, packages/vscode/test/grammar/fixtures/attributes.astro.snap
Fixes https://github.com/withastro/language-tools/issues/815
Added a test
N/A
=> fix(syntax): Don't highlight attributes for HTML events that are not string with JS highlighting

.changeset/gold-eggs-sleep.md, packages/language-server/src/core/parseCSS.ts, packages/language-server/src/plugins/typescript/index.ts
Revert small unintended changes in https://github.com/withastro/language-tools/pull/900
N/A
=> Fixes regressions in script / style tag handling

.changeset/cuddly-moons-decide.md, packages/language-server/package.json, packages/language-server/test/typescript/scripts.test.ts, packages/vscode/package.json, pnpm-lock.yaml
Fixes https://github.com/withastro/language-tools/issues/928
Tests should pass!
N/A
=> chore: update compiler

.changeset/bright-coats-fry.md, packages/vscode/package.json, packages/vscode/syntaxes/mdx.astro.tmLanguage.json
- fix https://github.com/withastro/language-tools/issues/949
=> fix: Update Astro syntax highlighting for MDX files

packages/vscode/test/grammar/test.mjs
https://github.com/withastro/language-tools/pull/893 didn't quite fix things, trying an easier solution.
Should pass!
N/A
=> fix: grammar tests on Windows

CONTRIBUTING.md, package.json, pnpm-lock.yaml
=> chore: upgrade to pnpm 9

.changeset/proud-badgers-talk.md, .github/workflows/ci.yml
=> Attempt to fix Linux tests
